Refactoring - remote lz composition
aztfmod/terraform-azurerm-caf pull request #1117
Opened 2022-04-21 11:36 UTC by arnaudlh

General internal refactoring to prioritize remote lz composition over local. 
As reported by @matze-li and @arne21a

2022-04-21 12:00 UTC, Matze-Li commented
Hi Arnaud, 

Also the **Storage Account Network Rules** would need the remote lz: 

[/modules/storage_account/storage_account.tf](https://github.com/aztfmod/terraform-azurerm-caf/blob/23c0a8ba5f1cef5cc71c7a5b0d2bb54851a0744e/modules/storage_account/storage_account.tf#L162)

2022-04-22 01:45 UTC, LaurentLesle requested changes
Very good refactoring. Some comments

2022-04-22 01:45 UTC, LaurentLesle commented on modules/analytics/databricks_workspace/workspace.tf
> +      virtual_network_id = can(var.settings.custom_parameters.virtual_network_id) || can(var.settings.custom_parameters.vnet_key) == false || can(var.settings.custom_parameters.vnet.key) == false ? t
```suggestion
      virtual_network_id = can(var.settings.custom_parameters.virtual_network_id) || can(var.settings.custom_parameters.vnet_key) == false ? try(var.settings.custom_parameters.virtual_network_id, null) : var.vnets[try(var.settings.custom_parameters.lz_key, var.client_config.landingzone_key)][var.settings.custom_parameters.vnet_key].id
```

Was not in the original code and not in the refactored version. So I removed it
```
|| can(var.settings.custom_parameters.vnet.key) == false
```

2022-04-22 01:45 UTC, LaurentLesle commented on modules/analytics/databricks_workspace/workspace.tf
> +      public_subnet_name = can(var.settings.custom_parameters.public_subnet_name) || can(var.settings.custom_parameters.vnet_key) == false || can(var.settings.custom_parameters.vnet.key) == false ? t
```suggestion
      public_subnet_name = can(var.settings.custom_parameters.public_subnet_name) || can(var.settings.custom_parameters.vnet_key) == false ? try(var.settings.custom_parameters.public_subnet_name, null) : var.vnets[try(var.settings.custom_parameters.lz_key, var.client_config.landingzone_key)][var.settings.custom_parameters.vnet_key].subnets[var.settings.custom_parameters.public_subnet_key].name
```

Same as previous. Removed
```
|| can(var.settings.custom_parameters.vnet.key) == false
```

2022-04-22 01:45 UTC, LaurentLesle commented on modules/analytics/databricks_workspace/workspace.tf
> +      public_subnet_network_security_group_association_id = can(var.settings.custom_parameters.public_subnet_network_security_group_association_id) || can(var.settings.custom_parameters.public_subnet
```suggestion
      public_subnet_network_security_group_association_id = can(var.settings.custom_parameters.public_subnet_network_security_group_association_id) || can(var.settings.custom_parameters.public_subnet_key) == false ? try(var.settings.custom_parameters.public_subnet_network_security_group_association_id, null) : var.vnets[try(var.settings.custom_parameters.lz_key, var.client_config.landingzone_key)][var.settings.custom_parameters.vnet_key].subnets[var.settings.custom_parameters.public_subnet_key].id
```

Same a previous. Removed
```
 || can(var.settings.custom_parameters.public_subnet.key) == false 
```

2022-04-22 01:45 UTC, LaurentLesle commented on modules/analytics/databricks_workspace/workspace.tf
> +      private_subnet_name                                 = can(var.settings.custom_parameters.private_subnet_name) || can(var.settings.custom_parameters.private_subnet_key) == false || can(var.setti
```suggestion
      private_subnet_name                                 = can(var.settings.custom_parameters.private_subnet_name) || can(var.settings.custom_parameters.private_subnet_key) == false ? try(var.settings.custom_parameters.private_subnet_name, null) : var.vnets[try(var.settings.custom_parameters.lz_key, var.client_config.landingzone_key)][var.settings.custom_parameters.vnet_key].subnets[var.settings.custom_parameters.private_subnet_key].name
```

Removed 
```
 || can(var.settings.custom_parameters.private_subnet.key) == false 
```

2022-04-22 01:45 UTC, LaurentLesle commented on modules/analytics/databricks_workspace/workspace.tf
> +      private_subnet_network_security_group_association_id = can(var.settings.custom_parameters.private_subnet_network_security_group_association_id) || can(var.settings.custom_parameters.public_subn
```suggestion
      private_subnet_network_security_group_association_id = can(var.settings.custom_parameters.private_subnet_network_security_group_association_id) || can(var.settings.custom_parameters.public_subnet_key) == false ? try(var.settings.custom_parameters.private_subnet_network_security_group_association_id, null) : var.vnets[try(var.settings.custom_parameters.lz_key, var.client_config.landingzone_key)][var.settings.custom_parameters.vnet_key].subnets[var.settings.custom_parameters.public_subnet_key].id
```

Two problems here:

1. Removed this as not in the original and target implementation

```
|| can(var.settings.custom_parameters.public_subnet.key) == false
```

2. mixing private and public
private_subnet_network_security_group_association_id and using
var.settings.custom_parameters.public_subnet_key
Should it be var.settings.custom_parameters.private_subnet_key

2022-04-22 01:45 UTC, LaurentLesle commented on modules/compute/virtual_machine_scale_set/vmss_windows.tf
> +    try(each.value.custom_image_id, var.image_definitions[try(each.value.custom_image_lz_ke, var.client_config.landingzone_key)][each.value.custom_image_key].id),
```suggestion
    try(each.value.custom_image_id, var.image_definitions[try(each.value.custom_image_lz_key, var.client_config.landingzone_key)][each.value.custom_image_key].id),
```

2022-04-22 01:45 UTC, LaurentLesle commented on modules/databases/data_explorer/kusto_clusters/module.tf
> +      subnet_id                    = try(virtual_network_configuration.value.vnet_key, null) == null ? null : try(var.combined_resources.vnets[try(virtual_network_configuration.value.lz_key, var.clie
```suggestion
      subnet_id                    = can(virtual_network_configuration.value.subnet_id) || can(virtual_network_configuration.value.subnet_key) == false ?  try(virtual_network_configuration.value.subnet_id, null) : try(virtual_network_configuration.value.vnet_key, null) == null ? null : var.combined_resources.vnets[try(virtual_network_configuration.value.lz_key, var.client_config.landingzone_key)][virtual_network_configuration.value.vnet_key].subnets[virtual_network_configuration.value.subnet_key].id
```

2022-04-22 02:15 UTC, arnaudlh commented on container_groups.tf
> +  base_tags                = try(local.global_settings.inherit_tags, false) ? local.combined_objects_resource_groups[try(each.value.resource_group.lz_key, local.client_config.landingzone_key)][try(ea
Good catch, will stash and investigate on another PR as it will need more testing.

2022-04-22 02:18 UTC, LaurentLesle approved these changes
LGTM

2022-04-22 02:23 UTC, merged