add optional encryption_at_host_enabled value
aztfmod/terraform-azurerm-caf pull request #1212
Opened 2022-06-15 12:26 UTC by kiebrew

# [Issue-id](https://github.com/aztfmod/terraform-azurerm-caf/issues/ISSUE-ID-GOES-HERE)

## PR Checklist

---

- [ ] I have added example(s) inside the [./examples/] folder
- [ ] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- [x] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [x] I have checked to ensure there aren't other open Pull Requests for the same update/change?

## Description
Simple change which adds the optional encyrption_at_host_enabled parameter to the existing Azure Windows VM Module. This is now supported within the azurerm terraform provider: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine#encryption_at_host_enabled

## Does this introduce a breaking change

- [ ] YES
- [x] NO

## Testing

2022-06-16 03:41 UTC, arnaudlh requested changes
Can you please review as per suggestion, and add the same for Linux VM if applicable?

2022-06-16 03:41 UTC, arnaudlh commented on modules/compute/virtual_machine/vm_windows.tf
> +  encryption_at_host_enabled   = try(each.encryption_at_host_enabled, null)
```suggestion
  encryption_at_host_enabled   = try(each.value.encryption_at_host_enabled, null)  
```

2022-06-16 08:05 UTC, kiebrew reviewed
Updated using proper syntax and added setting to Linux VM, which is also supported within the azurerm_linux_virtual_machine provider:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine#encryption_at_host_enabled

2022-06-17 02:23 UTC, arnaudlh approved these changes
LGTM, thanks for the update!

2022-06-17 02:25 UTC, merged