fix(modules/azurerm_api_management_custom_domain/module.tf): fixing w…
aztfmod/terraform-azurerm-caf pull request #1318
Opened 2022-08-30 16:36 UTC by nusrath432

…arning proxy is deprecated and will be renamed to gateway

Ref: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_custom_domain

# [1317](https://github.com/aztfmod/terraform-azurerm-caf/issues/1317)

## PR Checklist

---

- [ ] I have added example(s) inside the [./examples/] folder
- [ ] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- [X] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [X] I have checked to ensure there aren't other open Pull Requests for the same update/change?

## Description

Fix deprecated Warning "proxy is deprecated and will be renamed to gateway in version 3.0 of the AzureRM provider"

## Does this introduce a breaking change

- [ ] YES
- [X] NO

## Testing

2022-09-12 14:32 UTC, nusrath432 commented on aks_clusters.tf
> +      for group_key in try(each.value.admin_groups.azuread_groups_keys, {}) : local.combined_objects_azuread_groups[local.client_config.landingzone_key][group_key].id
@arnaudlh 
Not sure, if the "for...in..." expression is actually working, without the try/{} block, it fails:

```
  admin_group_object_ids = try(each.value.admin_groups.azuread_group_keys, null) == null ? null : try(
    each.value.admin_groups.ids,
    [
      for group_key in each.value.admin_groups.azuread_groups_keys : local.combined_objects_azuread_groups[local.client_config.landingzone_key][group_key].id
    ]
  )
```
Should be something like this:
```
  # admin_group_object_ids = can(each.value.admin_groups) == false ? null : try(
  #   each.value.admin_groups.ids,
  #   [
  #     for group_key in try(each.value.admin_groups.azuread_groups_keys,each.value.admin_groups.azuread_groups.keys) : local.combined_objects_azuread_groups[try(each.value.admin_groups.azuread_groups.lz_key, local.client_config.landingzone_key][group_key].id
  #   ]
  # )
```
But it should work if we define the block as:
```
    admin_groups = {
      # ids = ["12345c2e-6500-4684-b734-dd01c2dbc00d"] #
      azuread_group_keys = ["aks_cluster_admins"]
      # azuread_groups = {
      #   keys = ["aks_cluster_admins"]
      #  lz_key = "another-landingzone"
      # }
    }
```

The for...in expression should be evaluated.

2022-10-10 06:14 UTC, arnaudlh commented on aks_clusters.tf
> +      for group_key in try(each.value.admin_groups.azuread_groups_keys, {}) : local.combined_objects_azuread_groups[local.client_config.landingzone_key][group_key].id
@LaurentLesle any opinion on this one?

2022-11-17 10:30 UTC, nusrath432 commented
@LaurentLesle  Any update on this PR review please?

2022-11-17 10:31 UTC, nusrath432 commented on aks_clusters.tf
> +      for group_key in try(each.value.admin_groups.azuread_groups_keys, {}) : local.combined_objects_azuread_groups[local.client_config.landingzone_key][group_key].id
@LaurentLesle any update on this one please?

2022-12-18 23:03 UTC, nusrath432 commented
@arnaudlh @LaurentLesle Any idea when this PR will be approved, please?

2023-01-20 19:58 UTC, nusrath432 commented
@arnaudlh @LaurentLesle any updates on this PR please - its several months now.

2023-04-28 05:27 UTC, LaurentLesle commented
@nusrath432 I have changed the target branch for your PR. Can you merged int-5.7.0 into you branch to fix the conflicts? Then I think we are good to go.

2023-04-28 23:34 UTC, nusrath432 commented
@LaurentLesle @arnaudlh Conflicts resolved. Ta

2023-05-04 09:46 UTC, LaurentLesle requested changes
I have updated my comments. Can you address them? Thanks

2023-05-04 09:46 UTC, LaurentLesle commented on modules/databases/postgresql_flexible_server/databases.tf
> -resource "azurecaf_name" "postgresql_flexible_server_database" {
After review,  we prefer to keep the azurecaf_name. 
The proposed change is a breaking change and would require a lifecycle on the name. To prevent that, I propose you add an override on the passthrough

2023-05-04 09:46 UTC, LaurentLesle commented on modules/databases/postgresql_flexible_server/databases.tf
> -  passthrough   = var.global_settings.passthrough
passthrough = try(each.value.passthrough, false) ? true : var.global_settings.passthrough

2023-05-04 09:46 UTC, LaurentLesle commented on aks_clusters.tf
> +      for group_key in try(each.value.admin_groups.azuread_groups_keys, {}) : local.combined_objects_azuread_groups[local.client_config.landingzone_key][group_key].id
Let's keep: azuread_group.keys (keys part of azuread_group). easier to set the lz_key (remote groups) and the ids (by object_ids)

Let me know if that code is working and will approve the PR
```suggestion
      for group_key in try(each.value.admin_groups.azuread_group.keys, {}) : 
      coalesce(      
        try( local.combined_objects_azuread_groups[each.value.admin_groups.lz_key][group_key].id, null ),
        try( local.combined_objects_azuread_groups[local.client_config.landingzone_key][group_key].id, null )
      )
```

2023-05-04 21:57 UTC, nusrath432 commented
@LaurentLesle  I have updated the code as per your comments - unfortunately I have no access to a tenant to test.

2023-05-25 01:30 UTC, merged