Add Rewrite Rule feature to Application Gateway v1
aztfmod/terraform-azurerm-caf pull request #1368
Opened 2022-09-29 03:49 UTC by iriahk89

# [Issue-id](https://github.com/aztfmod/terraform-azurerm-caf/issues/ISSUE-ID-GOES-HERE)

## PR Checklist

---

- [ ] I have added example(s) inside the [./examples/] folder
- [ ] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- [ ] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [ ] I have checked to ensure there aren't other open Pull Requests for the same update/change?

## Description

## Does this introduce a breaking change

- [ ] YES
- [ ] NO

## Testing

2022-10-10 07:47 UTC, arnaudlh requested changes
Lets check on the cycle errors.

2022-10-10 07:47 UTC, arnaudlh commented on modules/networking/application_gateway_application/probe.tf
> +  depends_on = [null_resource.set_http_settings, null_resource.set_backend_pools, null_resource.set_http_listener, null_resource.set_ssl_cert, null_resource.set_root_cert, null_resource.set_rewrite_r
On testing, im getting cycle error on those dependencies, can we simplify maybe? :)

2022-10-11 01:34 UTC, iriahk89 commented on modules/networking/application_gateway_application/probe.tf
> +  depends_on = [null_resource.set_http_settings, null_resource.set_backend_pools, null_resource.set_http_listener, null_resource.set_ssl_cert, null_resource.set_root_cert, null_resource.set_rewrite_r
not sure if we can as the base is AZ CLI and we need to execute one by one. no parallel execution should happen if not it will fail. so that's the reason behind "depends on" to force the execution run by sequence

2022-10-14 04:06 UTC, arnaudlh approved these changes
LGTM

2022-10-14 04:07 UTC, merged