invalid express_route key value
aztfmod/terraform-azurerm-caf pull request #1402
Opened 2022-10-23 01:51 UTC by hriaz

changed to express_route_key from express_route.key

# [Issue-id](https://github.com/aztfmod/terraform-azurerm-caf/issues/ISSUE-ID-GOES-HERE)

## PR Checklist

---

- [ ] I have added example(s) inside the [./examples/] folder
- [ ] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- [ ] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [ ] I have checked to ensure there aren't other open Pull Requests for the same update/change?

## Description

## Does this introduce a breaking change

- [ ] YES
- [ ] NO

## Testing

2022-11-01 09:41 UTC, arnaudlh requested changes
Thanks for the PR @hriaz, please review and validate my suggested change.

2022-11-01 09:41 UTC, arnaudlh commented on networking_express_route.tf
> +  resource_group_name        = can(each.value.resource_group_name) ? each.value.resource_group_name : local.combined_objects_express_route_circuits[try(each.value.express_route.lz_key, local.client_c
```suggestion
  resource_group_name        = can(each.value.resource_group_name) ? each.value.resource_group_name : local.combined_objects_express_route_circuits[try(each.value.express_route.lz_key, local.client_config.landingzone_key)][try(each.value.express_route.key, each.value.express_route_key)].resource_group_name
```

2022-11-01 09:41 UTC, arnaudlh commented on networking_express_route.tf
> +  express_route_circuit_name = can(each.value.express_route_circuit_name) ? each.value.express_route_circuit_name : local.combined_objects_express_route_circuits[try(each.value.express_route.lz_key,
```suggestion
  express_route_circuit_name = can(each.value.express_route_circuit_name) ? each.value.express_route_circuit_name : local.combined_objects_express_route_circuits[try(each.value.express_route.lz_key, local.client_config.landingzone_key)][try(each.value.express_route.key, each.value.express_route_key)].name
```

2022-11-01 09:44 UTC, hriaz commented
> Thanks for the PR @hriaz, please review and validate my suggested change.

@arnaudlh done

2022-11-02 07:07 UTC, arnaudlh approved these changes
lgtm

2022-11-02 07:07 UTC, merged