Ak sql mi
aztfmod/terraform-azurerm-caf pull request #144
Opened 2020-11-19 10:06 UTC by iriahk89

Initial Release of msi thats include

- sql mi (default)
- sql managed db (default and PointInTimeRestore)
- Azure Ad Administrator
- FailoverGroup
- DB Backup Short Term Retention Policies

and also included standard mssql_server failovergroup

#106

2020-11-25 04:26 UTC, LaurentLesle requested changes
Very good first version. Thanks @iriahk89 
Can you address the requested changes?

2020-11-25 04:26 UTC, LaurentLesle commented on examples/mssql_server/failover_groups/configuration.tfvars
> +    # primary_server_name = "test-sql-failover-source-server"
Cleanup those comments

2020-11-25 04:26 UTC, LaurentLesle commented on modules/databases/mssql_managed_instance/administrator/main.tf
> +  # # this is the format required by ARM templates
Cleanup please

2020-11-25 04:26 UTC, LaurentLesle commented on modules/databases/mssql_managed_instance/administrator/mi_administrator.tf
> +# resource "azurerm_template_deployment" "miadministrator" {
Cleanup

2020-11-25 04:26 UTC, LaurentLesle commented on modules/databases/mssql_managed_instance/administrator/arm_mi_administrator.json
> +{
Still using the ARM template to set admins? if not cleanup

2020-11-30 05:49 UTC, arnaudlh approved these changes

2020-11-30 07:14 UTC, merged