Add Web PubSub service
aztfmod/terraform-azurerm-caf pull request #1483
Opened 2023-01-04 18:16 UTC by schefa

# [Issue-id: 1348](https://github.com/aztfmod/terraform-azurerm-caf/issues/1348)

## PR Checklist

---

- [x] I have added example(s) inside the [./examples/] folder
- [ ] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- [x] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [x] I have checked to ensure there aren't other open Pull Requests for the same update/change?

## Description

This PR adds Web PubSub service.

## Does this introduce a breaking change

- [ ] YES
- [x] NO

## Testing

Go to `examples/`
Run 
- az login
- terraform init
- terraform plan -var-file examples/messaging/web_pubsub/100-simple-web-pubsub/configuration.tfvars
- terraform plan -var-file examples/messaging/web_pubsub/101-web-pubsub-hub/configuration.tfvars
- terraform plan -var-file examples/messaging/web_pubsub/102-web-pubsub-usermsi/configuration.tfvars
- terraform plan -var-file examples/messaging/web_pubsub/103-web-pubsub-keyvault/configuration.tfvars

2023-01-31 02:42 UTC, arnaudlh requested changes
Couple of suggested changes. 
thanks.

2023-01-31 02:42 UTC, arnaudlh commented on examples/messaging/web_pubsub/103-web-pubsub-keyvault/configuration.tfvars
> +    resource_group_key  = "test"
```suggestion
    resource_group_key  = "wps_examples"
```

2023-01-31 02:42 UTC, arnaudlh commented on modules/messaging/web_pubsub/hub/web_pubsub_hub.tf
> +resource "azurecaf_name" "hub" {
```suggestion
data "azurecaf_name" "hub" {
```

2023-01-31 02:42 UTC, arnaudlh commented on modules/messaging/web_pubsub/hub/web_pubsub_hub.tf
> +  name          = azurecaf_name.hub.result
```suggestion
  name          = data.azurecaf_name.hub.result
```

2023-01-31 02:42 UTC, arnaudlh commented on modules/messaging/web_pubsub/web_pubsub.tf
> +resource "azurecaf_name" "wps" {
```suggestion
data "azurecaf_name" "wps" {
```

2023-01-31 02:42 UTC, arnaudlh commented on modules/messaging/web_pubsub/web_pubsub.tf
> +  name                          = azurecaf_name.wps.result
```suggestion
  name                          = data.azurecaf_name.wps.result
```

2023-02-02 20:41 UTC, schefa commented on modules/messaging/web_pubsub/web_pubsub.tf
> +  name                          = azurecaf_name.wps.result
thx, done

2023-02-02 20:41 UTC, schefa commented on modules/messaging/web_pubsub/web_pubsub.tf
> +resource "azurecaf_name" "wps" {
thx, done

2023-02-02 20:41 UTC, schefa commented on modules/messaging/web_pubsub/hub/web_pubsub_hub.tf
> +  name          = azurecaf_name.hub.result
thx, done

2023-02-02 20:41 UTC, schefa commented on modules/messaging/web_pubsub/hub/web_pubsub_hub.tf
> +resource "azurecaf_name" "hub" {
thx, done

2023-02-02 20:42 UTC, schefa commented on examples/messaging/web_pubsub/103-web-pubsub-keyvault/configuration.tfvars
> +    resource_group_key  = "test"
thx, done

2023-02-02 20:44 UTC, schefa commented
@arnaudlh requested changes have been applied

2023-02-10 03:40 UTC, arnaudlh requested changes
Code seems ok, examples are not running so need minor changes.

2023-02-10 03:40 UTC, arnaudlh commented on examples/messaging/web_pubsub/101-web-pubsub-hub/configuration.tfvars
> +  hub2 = {
Comment this test since ```web_pubsub_id``` wont run since the literals dont exist.

2023-02-10 03:40 UTC, arnaudlh commented on examples/messaging/web_pubsub/103-web-pubsub-keyvault/configuration.tfvars
> +keyvaults = {
Missing KeyVault access policies for the example to work.

2023-02-10 13:29 UTC, schefa commented on examples/messaging/web_pubsub/103-web-pubsub-keyvault/configuration.tfvars
> +keyvaults = {
thx @arnaudlh , done

2023-02-10 13:29 UTC, schefa commented on examples/messaging/web_pubsub/101-web-pubsub-hub/configuration.tfvars
> +  hub2 = {
thx @arnaudlh , done

2023-03-08 07:07 UTC, arnaudlh approved these changes
LGTM

2023-03-08 07:07 UTC, merged