Feat/shared image gallery update
aztfmod/terraform-azurerm-caf pull request #1535
Opened 2023-03-07 15:51 UTC by joeybdub

# [Issue-id](https://github.com/aztfmod/terraform-azurerm-caf/issues/ISSUE-ID-GOES-HERE)

## PR Checklist

---

- [ ] I have added example(s) inside the [./examples/] folder 
- [ ] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- [x ] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [ x] I have checked to ensure there aren't other open Pull Requests for the same update/change?

## Description

Adding support for [hyper_v_generation] (https://registry.terraform.io/providers/hashicorp/azurerm/2.88.1/docs/resources/shared_image#hyper_v_generation)

## Does this introduce a breaking change

- [ ] YES
- [ x] NO

## Testing

2023-03-08 06:52 UTC, LaurentLesle approved these changes
LGTM. Thanks for the PR

2023-03-08 06:54 UTC, arnaudlh requested changes
Thanks for your PR! Please review and update if agree!

2023-03-08 06:54 UTC, arnaudlh commented on modules/shared_image_gallery/image_definitions/Image_definitions.tf
> +  hyper_v_generation  = var.hyper_v_generation
```suggestion
  hyper_v_generation  = try(var.settings.hyper_v_generation, null)
```
I would suggest we catch it under the settings object and we put it as optional as it is in the provider: https://registry.terraform.io/providers/hashicorp/azurerm/2.99.0/docs/resources/shared_image#hyper_v_generation

2023-03-08 06:54 UTC, arnaudlh commented on modules/shared_image_gallery/image_definitions/variables.tf
> +variable "hyper_v_generation" {}
```suggestion
```
Under "settings" object config.

2023-03-09 09:24 UTC, joeybdub commented
I have update the code as requested @arnaudlh @LaurentLesle

2023-03-14 05:50 UTC, arnaudlh approved these changes
LGTM

2023-03-16 07:52 UTC, merged

2023-03-16 07:53 UTC, arnaudlh commented
thanks for your contribution @joeybdub!

2023-03-16 08:54 UTC, joeybdub commented
Thanks and I hope to have some more in the near future!