0.4 akeloth mysql
aztfmod/terraform-azurerm-caf pull request #155
Opened 2020-11-23 03:46 UTC by abhilash-keloth

Removed AD and added all other review feedbacks.

2020-11-25 04:13 UTC, LaurentLesle requested changes

2020-11-25 04:13 UTC, LaurentLesle commented on examples/mysql_server/100-simple-mysql/configuration.tfvars
> +    mysql_database = {
to be consistent with other services can you put a plural 'mysql_databases'

2020-11-25 04:13 UTC, LaurentLesle commented on examples/mysql_server/100-simple-mysql/configuration.tfvars
> +    mysql_configuration = {
o be consistent with other services can you put a plural 'mysql_configurations'

2020-11-25 04:13 UTC, LaurentLesle commented on examples/mysql_server/101-vnet-rule-mysql/configuration.tfvars
> +    mysql_configuration = {
plural

2020-11-25 04:13 UTC, LaurentLesle commented on examples/mysql_server/101-vnet-rule-mysql/configuration.tfvars
> +    mysql_database = {
plural

2020-11-25 04:13 UTC, LaurentLesle commented on examples/mysql_server/102-private-endpoint-mysql/configuration.tfvars
> +    mysql_configuration = {
plural

2020-11-25 04:13 UTC, LaurentLesle commented on examples/mysql_server/102-private-endpoint-mysql/configuration.tfvars
> +    mysql_database = {
plural

2020-11-25 04:13 UTC, LaurentLesle commented on examples/mysql_server/102-private-endpoint-mysql/configuration.tfvars
> +        }
remote_tstate is not required anymore. Plese delete the block

2020-11-25 04:13 UTC, LaurentLesle commented on examples/mysql_server/103-private-endpoint-with-fw-rule-mysql/configuration.tfvars
> +    mysql_database = {
plural

2020-11-25 04:13 UTC, LaurentLesle commented on examples/mysql_server/103-private-endpoint-with-fw-rule-mysql/configuration.tfvars
> +        }
remote_tstate is not required anymore. Plese delete the block

2020-11-25 04:13 UTC, LaurentLesle commented on examples/mysql_server/103-private-endpoint-with-fw-rule-mysql/configuration.tfvars
> +        enforce_private_link_endpoint_network_policies = "true"
make sure you run the terraform fmt --recursive /tf/caf

2020-11-25 04:13 UTC, LaurentLesle commented on modules/databases/mysql_server/configuration.tf
> +  for_each = var.settings.mysql_configuration
plural (configurations)

2020-11-25 04:13 UTC, LaurentLesle commented on modules/databases/mysql_server/database.tf
> +  for_each = var.settings.mysql_database
plural

2020-11-30 02:48 UTC, abhilash-keloth commented on examples/mysql_server/101-vnet-rule-mysql/configuration.tfvars
> +    mysql_configuration = {
done

2020-12-22 05:33 UTC, arnaudlh approved these changes

2020-12-22 05:52 UTC, merged