Added AKS Preview registration, Workload Identity
aztfmod/terraform-azurerm-caf pull request #1578
Opened 2023-04-19 15:50 UTC by hieumoscow

# [Issue-id](https://github.com/aztfmod/terraform-azurerm-caf/issues/ISSUE-ID-GOES-HERE)

## PR Checklist

---

- [ ] I have added example(s) inside the [./examples/] folder
- [ ] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- [ ] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [ ] I have checked to ensure there aren't other open Pull Requests for the same update/change?

## Description

## Does this introduce a breaking change

- [ ] YES
- [ ] NO

## Testing

2023-04-24 04:14 UTC, arnaudlh approved these changes
LGTM

2023-04-27 10:37 UTC, arnaudlh requested changes
LGTM, please review change in the bash string processing.

2023-04-27 10:37 UTC, arnaudlh commented on preview_features.tf
> +        if [ "$feature_status" == "Registered" ]; then
```suggestion
        if [ -n "$feature_status" ] && [ "$feature_status" = "Registered" ]; then
```

2023-04-27 11:42 UTC, LaurentLesle approved these changes
LGTM.  More generic to support other preview features.

2023-04-27 11:43 UTC, arnaudlh approved these changes
Good

2023-04-27 11:43 UTC, merged