Added option to directly use a custom key id for disk encryption set.
aztfmod/terraform-azurerm-caf pull request #1582
Opened 2023-04-24 09:46 UTC by shanoor

## PR Checklist

- [ ] I have added example(s) inside the [./examples/] folder
- [ ] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- [x] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [x] I have checked to ensure there aren't other open Pull Requests for the same update/change?

## Description

Added option to directly use a custom key id for disk encryption set.

## Does this introduce a breaking change

- [ ] YES
- [x] NO

## Testing

```
disk_encryption_sets = {
  set1 = {
    name               = "DSE001"
    resource_group_key = "dse"
    key_vault_key_id   = "https://keyvault001.vault.azure.net/keys/dse-cmk/fec2d7f7b8014cf0980551ce30dfec57"
  }
}
```

2023-04-24 10:08 UTC, arnaudlh requested changes
Please check if the refactoring for ```key_vault_key_id``` is working for you. 

This is to force the evaluation of ```key_vault_key_id``` at plan time (hence more stable and no issue when you add/delete keys).

2023-04-24 10:08 UTC, arnaudlh commented on disk_encryption_sets.tf
> +  key_vault_key_id    = try(each.value.key_vault_key_id, local.combined_objects_keyvault_keys[try(each.value.keyvault_key.lz_key, local.client_config.landingzone_key)][try(each.value.key_vault_key_ke
```suggestion
  key_vault_key_id    = can(each.value.key_vault_key_id) ?  each.value.key_vault_key_id : local.combined_objects_keyvault_keys[try(each.value.keyvault_key.lz_key, local.client_config.landingzone_key)][try(each.value.key_vault_key_key, each.value.key_vault_key.key)].id)
```

2023-04-25 12:32 UTC, shanoor commented on disk_encryption_sets.tf
> +  key_vault_key_id    = try(each.value.key_vault_key_id, local.combined_objects_keyvault_keys[try(each.value.keyvault_key.lz_key, local.client_config.landingzone_key)][try(each.value.key_vault_key_ke
I made the change, it works just fine 👍

2023-04-26 02:29 UTC, LaurentLesle requested changes
Thanks @shanoor for the PR. I have added some comments. Can you address them first?

2023-04-26 02:29 UTC, LaurentLesle commented on disk_encryption_sets.tf
> +  keyvault_id         = try(each.value.key_vault_key_id, null) == null ? local.combined_objects_keyvaults[try(each.value.keyvault.lz_key, local.client_config.landingzone_key)][each.value.keyvault.key
We are trying to leverage the can() when adding an option to reference the id of an object. Let me know if the following is working for you?

```suggestion
  keyvault_id         = can(each.value.key_vault_key_id) ? null : local.combined_objects_keyvaults[try(each.value.keyvault.lz_key, local.client_config.landingzone_key)][each.value.keyvault.key].id
```

2023-04-26 02:29 UTC, LaurentLesle commented on modules/security/disk_encryption_set/keyvault_policy.tf
> +  count        = try(var.keyvault_id, null) == null ? 0 : 1
Suggest you update the variable keyvault_id like

```
variable keyvault_id {
 default = null
}
```

With that variable default set to null you don't need to add the try()
```suggestion
  count        = var.keyvault_id == null ? 0 : 1
```

2023-04-26 09:02 UTC, shanoor commented on modules/security/disk_encryption_set/keyvault_policy.tf
> +  count        = try(var.keyvault_id, null) == null ? 0 : 1
I made the change, it works :)

2023-04-27 06:34 UTC, arnaudlh approved these changes
LGTM

2023-04-27 09:12 UTC, LaurentLesle requested changes
See my comments

2023-04-27 09:12 UTC, LaurentLesle commented on modules/security/disk_encryption_set/keyvault_policy.tf
I can see you are setting the keyvault_id optional. Are you planning to grant the disk encryption permission outside of this code? To get the key, the DES need to have a policy set to get, warp and unwarp the key

2023-04-27 09:12 UTC, LaurentLesle commented on disk_encryption_sets.tf
> +  key_vault_key_id    = can(each.value.key_vault_key_id) ? each.value.key_vault_key_id : local.combined_objects_keyvault_keys[try(each.value.keyvault_key.lz_key, local.client_config.landingzone_key)]
Suggest you add as well the nested variable
```suggestion
  key_vault_key_id    = can(each.value.key_vault_key_id) || can(each.value.key_vault_key.id) ? try(each.value.key_vault_key_id, each.value.key_vault_key.id) : local.combined_objects_keyvault_keys[try(each.value.keyvault_key.lz_key, local.client_config.landingzone_key)][try(each.value.key_vault_key_key, each.value.key_vault_key.key)].id
```

2023-05-02 12:16 UTC, shanoor commented on modules/security/disk_encryption_set/keyvault_policy.tf
Yes, we are in a situation where the key is stored in a keyvault managed by another team, so they are responsible for creating the policy, we just need to consume the key by using its direct URL.

2023-05-02 13:04 UTC, shanoor commented on disk_encryption_sets.tf
> +  key_vault_key_id    = can(each.value.key_vault_key_id) ? each.value.key_vault_key_id : local.combined_objects_keyvault_keys[try(each.value.keyvault_key.lz_key, local.client_config.landingzone_key)]
Works for me

2023-05-03 09:36 UTC, merged