Feature/private dns resolver
aztfmod/terraform-azurerm-caf pull request #1584
Opened 2023-04-25 09:12 UTC by raketham

# [Issue-id](https://github.com/aztfmod/terraform-azurerm-caf/issues/ISSUE-ID-GOES-HERE)

## PR Checklist

---

- [ ] I have added example(s) inside the [./examples/] folder
- [ ] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- [ ] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [ ] I have checked to ensure there aren't other open Pull Requests for the same update/change?

## Description

## Does this introduce a breaking change

- [ ] YES
- [ ] NO

## Testing

2023-04-26 03:55 UTC, LaurentLesle requested changes
Hi @raketham . This is a very good PR. Thank you very much for your first contribution. I have added some suggestions to align with the rest of the aztfmod coding standard.
Also note I have proposed you revert back the subnet delegate.name you propose to stay with the current implementation. I have provided an example with SQL MI.

2023-04-26 03:55 UTC, LaurentLesle commented on examples/networking/private_dns_resolvers/configuration.tfvars
> +    delegation = {
We have a legacy to maintain. I agree you approach should have been the way to go but I will have to ask you to update it to follow SQL
Also you will have to revert the change in the subnet file
```hcl
delegation = {
          name               = "sqlmidelegation"
          service_delegation = "Microsoft.Sql/managedInstances"
          actions = [
            "Microsoft.Network/virtualNetworks/subnets/join/action",
            "Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action",
            "Microsoft.Network/virtualNetworks/subnets/unprepareNetworkPolicies/action"
          ]
        }
```

2023-04-26 03:55 UTC, LaurentLesle commented on modules/networking/virtual_network/subnet/subnet.tf
> +        name    = var.settings.delegation.service_delegation.name
```suggestion
        name    = var.settings.delegation.service_delegation
```

2023-04-26 03:55 UTC, LaurentLesle commented on networking_private_dns_resolver_dns_forwarding_rules.tf
> +  dns_forwarding_ruleset_id = can(each.value.dns_forwarding_ruleset.id) ? try(each.value.dns_forwarding_ruleset.id, null) : local.combined_objects_private_dns_resolver_dns_forwarding_rulesets[try(eac
```suggestion
  dns_forwarding_ruleset_id = can(each.value.dns_forwarding_ruleset.id) ? each.value.dns_forwarding_ruleset.id : local.combined_objects_private_dns_resolver_dns_forwarding_rulesets[try(each.value.dns_forwarding_ruleset.lz_key, local.client_config.landingzone_key)][each.value.dns_forwarding_ruleset.key].id
```

2023-04-26 03:55 UTC, LaurentLesle commented on networking_private_dns_resolver_dns_forwarding_rulesets.tf
> +  location        = try(local.global_settings.regions[each.value.region], each.value.region)
```suggestion
  location        = try(local.global_settings.regions[each.value.region], null)
```

2023-04-26 03:55 UTC, LaurentLesle commented on networking_private_dns_resolver_dns_forwarding_rulesets.tf
> +      can(value.id) ? try(value.id, null) : try(local.combined_objects_private_dns_resolver_outbound_endpoints[try(value.lz_key, local.client_config.landingzone_key)][value.key].id, "")
I remove the try to let the resolution fails if the key does not resolve to the private_dns_resolver_outbound_endpoints. If you keep the try(...., "") it will silently fails which is not the intent

```suggestion
      can(value.id) ? value.id : local.combined_objects_private_dns_resolver_outbound_endpoints[try(value.lz_key, local.client_config.landingzone_key)][value.key].id
```

2023-04-26 03:55 UTC, LaurentLesle commented on modules/networking/private_dns_resolvers_dns_forwarding_rulesets/main.tf
> +  ) : null
```suggestion
  ) : null
  
  location            = coalesce(var.location, var.resource_group.location)
  resource_group_name = coalesce(var.resource_group_name, var.resource_group.name)
```

2023-04-26 03:55 UTC, LaurentLesle commented on modules/networking/private_dns_resolvers_dns_forwarding_rulesets/module.tf
> +  resource_group_name                        = var.resource_group
```suggestion
  resource_group_name                        = local.resource_group_name
```

2023-04-26 03:55 UTC, LaurentLesle commented on modules/networking/private_dns_resolvers_dns_forwarding_rulesets/module.tf
> +  location                                   = var.location
```suggestion
  location                                   = local.location
```

2023-04-26 03:55 UTC, LaurentLesle commented on modules/networking/private_dns_resolvers_dns_forwarding_rulesets/module.tf
> +resource "azurecaf_name" "pvtdnsrfrs" {
```suggestion
data "azurecaf_name" "pvtdnsrfrs" {
```

2023-04-26 03:55 UTC, LaurentLesle commented on modules/networking/private_dns_resolvers_dns_forwarding_rulesets/module.tf
> +  name                                       = azurecaf_name.pvtdnsrfrs.result
```suggestion
  name                                       = data.azurecaf_name.pvtdnsrfrs.result
```

2023-04-26 03:55 UTC, LaurentLesle commented on locals.combined_objects.tf
> +  combined_objects_private_dns_resolver_outbound_endpoints        = merge(tomap({ (local.client_config.landingzone_key) = module.private_dns_resolver_outbound_endpoints }), try(var.remote_objects.pri
Add combined_objects_private_dns_resolver_inbound_endpoints as it will be required for a future PR for vnet DNS_SERVERS. We have a mecanism to reference the private ip of an azure firewall, vm or load balancer as the private dns servers. private_dns_resolver_inbound_endpoints will be added to that list and required to be added in the combined objects
```suggestion
  combined_objects_private_dns_resolver_inbound_endpoints        = merge(tomap({ (local.client_config.landingzone_key) = module.private_dns_resolver_inbound_endpoints }), try(var.remote_objects.private_dns_resolver_inbound_endpoints, {}))
  combined_objects_private_dns_resolver_outbound_endpoints        = merge(tomap({ (local.client_config.landingzone_key) = module.private_dns_resolver_outbound_endpoints }), try(var.remote_objects.private_dns_resolver_outbound_endpoints, {}))
  
```

2023-04-26 03:55 UTC, LaurentLesle commented on networking_private_dns_resolver_inbound_endpoints.tf
> +  private_dns_resolver_id = can(each.value.private_dns_resolver_id) ? each.value.private_dns_resolver_id : local.combined_objects_private_dns_resolvers[try(each.value.private_dns_resolver.lz_key, loc
To be consistent with other changes
```suggestion
  private_dns_resolver_id = can(each.value.private_dns_resolver_id) || can(each.value.private_dns_resolver.id) ? try(each.value.private_dns_resolver_id, each.value.private_dns_resolver.id) : local.combined_objects_private_dns_resolvers[try(each.value.private_dns_resolver.lz_key, local.client_config.landingzone_key)][each.value.private_dns_resolver.key].id
```

2023-04-26 03:55 UTC, LaurentLesle commented on networking_private_dns_resolver_inbound_endpoints.tf
> +  location                = try(local.global_settings.regions[each.value.region], each.value.region)
If the private dns resolver id is set we need the region to be set to get the location.
If not set then we pick it up from the private dns resolver
do the same for base tags
```suggestion
  location                = can(each.value.private_dns_resolver_id) || can(each.value.private_dns_resolver.id) || can(each.value.region) ? local.global_settings.regions[each.value.region] : local.combined_objects_private_dns_resolvers[try(each.value.private_dns_resolver.lz_key, local.client_config.landingzone_key)][each.value.private_dns_resolver.key].location
  tags = can(each.value.private_dns_resolver_id) || can(each.value.private_dns_resolver.id) || local.global_settings.inherit_tags == false ? null : try(local.combined_objects_private_dns_resolvers[try(each.value.private_dns_resolver.lz_key, local.client_config.landingzone_key)][each.value.private_dns_resolver.key].tags, {})
```

2023-04-26 03:55 UTC, LaurentLesle commented on modules/networking/private_dns_resolvers_inbound_endpoints/variables.tf
> +
You need to add a variable tags to get the base tags from the private_dns_resolver when inherit tags is set to true

```suggestion
variable "tags" {
  default = {}
}
```

2023-04-26 03:55 UTC, LaurentLesle commented on modules/networking/private-dns-resolvers/output.tf
> +}
You need to add tags and location to enable the private_dns_resolver_inbound_endpoint and private_dns_resolver_outbound_endpoint to pick those values as their default value.

2023-04-26 03:55 UTC, LaurentLesle commented on modules/networking/private_dns_resolvers_inbound_endpoints/main.tf
> +    var.global_settings.tags
```suggestion
    var.global_settings.tags,
    var.tags
```

2023-04-26 03:55 UTC, LaurentLesle commented on modules/networking/private_dns_resolvers_inbound_endpoints/module.tf
> +resource "azurecaf_name" "pvtdnsrie" {
```suggestion
data "azurecaf_name" "pvtdnsrie" {
```

2023-04-26 03:55 UTC, LaurentLesle commented on modules/networking/private_dns_resolvers_inbound_endpoints/module.tf
> +  name                    = azurecaf_name.pvtdnsrie.result
```suggestion
  name                    = data.azurecaf_name.pvtdnsrie.result
```

2023-04-26 03:55 UTC, LaurentLesle commented on modules/networking/private_dns_resolvers_inbound_endpoints/output.tf
> +}
add the private_ip_address as an output variable. check if the following is working

```suggestion
}

output "private_ip_address" {
  value = azurerm_private_dns_resolver_inbound_endpoint.pvt_dns_resolver_inbound_endpoint.ip_configurations[0].private_ip_address
}
```

2023-04-26 03:55 UTC, LaurentLesle commented on networking_private_dns_resolver_outbound_endpoints.tf
> +    can(each.value.subnet_id) || can(each.value.vnet.key) == false ? try(each.value.subnet_id, null) : try(local.combined_objects_virtual_subnets[try(each.value.vnet.lz_key, local.client_config.landi
```suggestion
    can(each.value.subnet_id) || can(each.value.vnet.key) == false ? each.value.subnet_id : try(local.combined_objects_virtual_subnets[try(each.value.vnet.lz_key, local.client_config.landingzone_key)][each.value.vnet.subnet_key].id,
```

2023-04-26 03:55 UTC, LaurentLesle commented on networking_private_dns_resolver_outbound_endpoints.tf
> +    can(each.value.subnet_id) || can(each.value.vnet.key) == false ? try(each.value.subnet_id, null) : try(local.combined_objects_networking[try(each.value.vnet.lz_key, local.client_config.landingzon
```suggestion
    local.combined_objects_networking[try(each.value.vnet.lz_key, local.client_config.landingzone_key)][each.value.vnet.key].subnets[each.value.vnet.subnet_key].id)
```

2023-04-26 03:55 UTC, LaurentLesle commented on networking_private_dns_resolver_outbound_endpoints.tf
> +    can(each.value.subnet_id) || can(each.value.vnet.key) == false ? try(each.value.subnet_id, null) : try(local.combined_objects_virtual_subnets[try(each.value.vnet.lz_key, local.client_config.landi
I propose a simplification. If no subnet id can be resolved then terraform will fail

2023-04-26 03:55 UTC, LaurentLesle commented on networking_private_dns_resolver_outbound_endpoints.tf
> +  location                = try(local.global_settings.regions[each.value.region], each.value.region)
Same as inbound
```suggestion
  location                = can(each.value.private_dns_resolver_id) || can(each.value.private_dns_resolver.id) || can(each.value.region) ? local.global_settings.regions[each.value.region] : local.combined_objects_private_dns_resolvers[try(each.value.private_dns_resolver.lz_key, local.client_config.landingzone_key)][each.value.private_dns_resolver.key].location
  tags = can(each.value.private_dns_resolver_id) || can(each.value.private_dns_resolver.id) || local.global_settings.inherit_tags == false ? null : try(local.combined_objects_private_dns_resolvers[try(each.value.private_dns_resolver.lz_key, local.client_config.landingzone_key)][each.value.private_dns_resolver.key].tags, {})
```

2023-04-26 03:55 UTC, LaurentLesle commented on networking_private_dns_resolver_outbound_endpoints.tf
> +  private_dns_resolver_id = can(each.value.private_dns_resolver_id) ? each.value.private_dns_resolver_id : local.combined_objects_private_dns_resolvers[try(each.value.private_dns_resolver.lz_key, loc
```suggestion
  private_dns_resolver_id = can(each.value.private_dns_resolver_id) || can(each.value.private_dns_resolver.id) ? try(each.value.private_dns_resolver_id, each.value.private_dns_resolver.id) : local.combined_objects_private_dns_resolvers[try(each.value.private_dns_resolver.lz_key, local.client_config.landingzone_key)][each.value.private_dns_resolver.key].id
```

2023-04-26 03:55 UTC, LaurentLesle commented on modules/networking/private_dns_resolvers_outbound_endpoints/main.tf
> +    var.global_settings.tags
```suggestion
    var.global_settings.tags,
    var.tags
```

2023-04-26 03:55 UTC, LaurentLesle commented on modules/networking/private_dns_resolvers_outbound_endpoints/variables.tf
> +
```suggestion
variable "tags" {
 default = null
}
```

2023-04-26 03:55 UTC, LaurentLesle commented on modules/networking/private_dns_resolvers_outbound_endpoints/module.tf
> +resource "azurecaf_name" "pvtdnsroe" {
```suggestion
data "azurecaf_name" "pvtdnsroe" {
```

2023-04-26 03:55 UTC, LaurentLesle commented on modules/networking/private_dns_resolvers_outbound_endpoints/module.tf
> +  name                    = azurecaf_name.pvtdnsroe.result
```suggestion
  name                    = data.azurecaf_name.pvtdnsroe.result
```

2023-04-26 03:55 UTC, LaurentLesle commented on modules/networking/private_dns_resolvers_forwarding_rules/module.tf
> +resource "azurecaf_name" "pvtdnsrfr" {
```suggestion
data "azurecaf_name" "pvtdnsrfr" {
```

2023-04-26 03:55 UTC, LaurentLesle commented on modules/networking/private_dns_resolvers_forwarding_rules/module.tf
> +  name                      = azurecaf_name.pvtdnsrfr.result
```suggestion
  name                      = data.azurecaf_name.pvtdnsrfr.result
```

2023-04-26 03:55 UTC, LaurentLesle commented on modules/networking/private_dns_resolvers_forwarding_rules/module.tf
> +  enabled                   = can(var.settings.enabled) ? try(var.settings.enabled, true) : true
Let the provider set the default value
```suggestion
  enabled                   = try(var.settings.enabled, null)
```

2023-04-26 03:55 UTC, LaurentLesle commented on modules/networking/private_dns_resolvers_forwarding_rules/module.tf
> +  metadata                  = can(var.settings.metadata) ? try(var.settings.metadata, {}) : {}
```suggestion
  metadata                  = try(var.settings.metadata, {})
```

2023-04-26 03:55 UTC, LaurentLesle commented on modules/networking/private_dns_resolvers_forwarding_rules/module.tf
> +      port       = can(target_dns_servers.value.port) ? try(target_dns_servers.value.port, 53) : 53
```suggestion
      port       = try(target_dns_servers.value.port, 53)
```

2023-04-27 04:20 UTC, LaurentLesle approved these changes
Very Good. Thanks. Let's test in the ci

2023-04-27 08:53 UTC, arnaudlh approved these changes
LGTM

2023-04-27 08:57 UTC, merged