Revert maintenance window settings
aztfmod/terraform-azurerm-caf pull request #1668
Opened 2023-06-22 15:50 UTC by caiovbraga

# [Issue-id](https://github.com/aztfmod/terraform-azurerm-caf/issues/ISSUE-ID-GOES-HERE)

## PR Checklist

---

- [ ] I have added example(s) inside the [./examples/] folder
- [ ] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- [ ] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [X] I have checked to ensure there aren't other open Pull Requests for the same update/change?

## Description

Reverting changes in aks `maintenance_window` dynamic block with previous `try` function.

`can` function introduces errors if value is null or not specified.

`not_allowed = null` - can function returns `true`
```
    maintenance_window = {
      not_allowed = null
      allowed = {
        day = "Saturday"
        hours = [
          8,
          9,
          10,
          11,
          12
        ]
      }
    }

│ Error: Attempt to get attribute from null value
│ 
│   on .terraform/modules/caf/modules/compute/aks/aks.tf line 312, in resource "azurerm_kubernetes_cluster" "aks":
│  312:           end   = var.settings.maintenance_window.not_allowed.end
│     ├────────────────
│     │ var.settings.maintenance_window.not_allowed is null
│ 
│ This value is null, so it does not have any attributes.
╵
╷
│ Error: Attempt to get attribute from null value
│ 
│   on .terraform/modules/caf/modules/compute/aks/aks.tf line 313, in resource "azurerm_kubernetes_cluster" "aks":
│  313:           start = var.settings.maintenance_window.not_allowed.start
│     ├────────────────
│     │ var.settings.maintenance_window.not_allowed is null
│ 
│ This value is null, so it does not have any attributes.
```

not specified

```
    maintenance_window = {
      allowed = {
        day = "Saturday"
        hours = [
          8,
          9,
          10,
          11,
          12
        ]
      }
    }

│ Error: Unsupported attribute
│ 
│   on .terraform/modules/caf/modules/compute/aks/aks.tf line 310, in resource "azurerm_kubernetes_cluster" "aks":
│  310:         for_each = var.settings.maintenance_window.not_allowed == null ? [] : [1]
│     ├────────────────
│     │ var.settings.maintenance_window is object with 1 attribute "allowed"
│ 
│ This object does not have an attribute named "not_allowed".
```

## Does this introduce a breaking change

- [ ] YES
- [x] NO

## Testing

2023-06-23 02:53 UTC, LaurentLesle commented
@caiovbraga which version are you testing? looks like the code you are testing is not using even the can
<img width="914" alt="image" src="https://github.com/aztfmod/terraform-azurerm-caf/assets/4702224/57664747-2653-4818-9acf-f2aba1b2d58f">

2023-06-23 07:23 UTC, caiovbraga commented
> @caiovbraga which version are you testing? looks like the code you are testing is not using even the can <img alt="image" width="914" src="https://user-images.githubusercontent.com/4702224/248141796-57664747-2653-4818-9acf-f2aba1b2d58f.png">

That would be in version **5.7.0**.

Here's the correct error I'm getting (in 5.7.0) if I don't specify a value for `not_allowed`:
```
    maintenance_window = {
      allowed = {
        day = "Saturday"
        hours = [
          8,
          9,
          10,
          11,
          12
        ]
      }
    }

Plan:
│ Error: Missing required argument
│ 
│   with module.caf.module.aks_clusters["cluster_re1"].azurerm_kubernetes_cluster.aks,
│   on .terraform/modules/caf/modules/compute/aks/aks.tf line 40, in resource "azurerm_kubernetes_cluster" "aks":
│   40: resource "azurerm_kubernetes_cluster" "aks" {
│ 
│ "maintenance_window.0.not_allowed": one of `maintenance_window.0.allowed,maintenance_window.0.not_allowed` must be specified
╵
╷
│ Error: Missing required argument
│ 
│   with module.caf.module.aks_clusters["cluster_re1"].azurerm_kubernetes_cluster.aks,
│   on .terraform/modules/caf/modules/compute/aks/aks.tf line 40, in resource "azurerm_kubernetes_cluster" "aks":
│   40: resource "azurerm_kubernetes_cluster" "aks" {
│ 
│ "maintenance_window.0.allowed": one of `maintenance_window.0.allowed,maintenance_window.0.not_allowed` must be specified
```

This worked fine up to version **5.6.9** with `not_allowed = null`
```
    maintenance_window = {
      allowed = {
        day = "Saturday"
        hours = [
          8,
          9,
          10,
          11,
          12
        ]
      }
      not_allowed = null
    }
```

2023-07-03 14:22 UTC, caiovbraga commented
> > @caiovbraga which version are you testing? looks like the code you are testing is not using even the can <img alt="image" width="914" src="https://user-images.githubusercontent.com/4702224/248141796-57664747-2653-4818-9acf-f2aba1b2d58f.png">
> 
> That would be in version **5.7.0**.
> 
> Here's the correct error I'm getting (in 5.7.0) if I don't specify a value for `not_allowed`:
> 
> ```
>     maintenance_window = {
>       allowed = {
>         day = "Saturday"
>         hours = [
>           8,
>           9,
>           10,
>           11,
>           12
>         ]
>       }
>     }
> 
> Plan:
> │ Error: Missing required argument
> │ 
> │   with module.caf.module.aks_clusters["cluster_re1"].azurerm_kubernetes_cluster.aks,
> │   on .terraform/modules/caf/modules/compute/aks/aks.tf line 40, in resource "azurerm_kubernetes_cluster" "aks":
> │   40: resource "azurerm_kubernetes_cluster" "aks" {
> │ 
> │ "maintenance_window.0.not_allowed": one of `maintenance_window.0.allowed,maintenance_window.0.not_allowed` must be specified
> ╵
> ╷
> │ Error: Missing required argument
> │ 
> │   with module.caf.module.aks_clusters["cluster_re1"].azurerm_kubernetes_cluster.aks,
> │   on .terraform/modules/caf/modules/compute/aks/aks.tf line 40, in resource "azurerm_kubernetes_cluster" "aks":
> │   40: resource "azurerm_kubernetes_cluster" "aks" {
> │ 
> │ "maintenance_window.0.allowed": one of `maintenance_window.0.allowed,maintenance_window.0.not_allowed` must be specified
> ```
> 
> This worked fine up to version **5.6.9** with `not_allowed = null`
> 
> ```
>     maintenance_window = {
>       allowed = {
>         day = "Saturday"
>         hours = [
>           8,
>           9,
>           10,
>           11,
>           12
>         ]
>       }
>       not_allowed = null
>     }
> ```

@LaurentLesle versions tested are 5.7.0 and 5.6.9. Results are in the comment above. Is there any more info I can provide?

2023-07-19 16:19 UTC, caiovbraga commented
Is there any information I need to provide? Tested as per comments above? Thank you

2023-07-26 08:22 UTC, arnaudlh requested changes
thanks for your PR @caiovbraga, are you able to test with the changes I suggested? It seemed to fine for me with a couple of combinations. please let me know!

2023-07-26 08:22 UTC, arnaudlh commented on modules/compute/aks/aks.tf
> +        for_each = var.settings.maintenance_window.allowed == null ? [] : [1]
```suggestion
        for_each = try(var.settings.maintenance_window.allowed, null) == null ? [] : [1]
```

2023-07-26 08:22 UTC, arnaudlh commented on modules/compute/aks/aks.tf
> +        for_each = var.settings.maintenance_window.not_allowed == null ? [] : [1]
```suggestion
        for_each = try(var.settings.maintenance_window.not_allowed, null) == null ? [] : [1]
```

2023-07-31 08:15 UTC, caiovbraga commented
> thanks for your PR @caiovbraga, are you able to test with the changes I suggested? It seemed to fine for me with a couple of combinations. please let me know!

@arnaudlh Looks good to me! Thank you

2023-08-09 09:34 UTC, arnaudlh approved these changes
LGTM

2023-08-09 09:36 UTC, merged

2023-08-09 09:36 UTC, arnaudlh commented
thanks for your contribution @caiovbraga!