Add missed parameters for the Azure Cosmos DB Account
aztfmod/terraform-azurerm-caf pull request #1671
Opened 2023-06-23 12:23 UTC by mdanylyuk

# [1670](https://github.com/aztfmod/terraform-azurerm-caf/issues/1670)

## PR Checklist

---

- [x] I have added example(s) inside the [./examples/] folder
- [ ] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- [x] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [x] I have checked to ensure there aren't other open Pull Requests for the same update/change?

## Description

## Does this introduce a breaking change

- [ ] YES
- [x] NO

I added new parameters for the managing security in the Cosmos DB Account (https://azure.github.io/cloud-scale-data-for-devs-guide/security.html#role-based-access-control)

## Testing

2023-06-27 07:58 UTC, arnaudlh requested changes
thanks for the PR @mdanylyuk.  I'd suggest we put ```null``` instead of a module enforced default value. We learnt that we want to let the provider default and usually not enforce an overide at module level.

2023-06-27 07:58 UTC, arnaudlh commented on modules/databases/cosmos_dbs/cosmosdb_account.tf
> +  access_key_metadata_writes_enabled  = try(var.settings.access_key_metadata_writes_enabled, true)
```suggestion
  access_key_metadata_writes_enabled  = try(var.settings.access_key_metadata_writes_enabled, null)
```

2023-06-27 07:58 UTC, arnaudlh commented on modules/databases/cosmos_dbs/cosmosdb_account.tf
> +  local_authentication_disabled       = try(var.settings.local_authentication_disabled, false)
```suggestion
  local_authentication_disabled       = try(var.settings.local_authentication_disabled, null)
```

2023-06-27 08:35 UTC, mdanylyuk commented on modules/databases/cosmos_dbs/cosmosdb_account.tf
> +  access_key_metadata_writes_enabled  = try(var.settings.access_key_metadata_writes_enabled, true)
Ok, changed it. But what's interesting there are lots other parameters with "true/false" as default value)

2023-06-27 08:36 UTC, mdanylyuk commented on modules/databases/cosmos_dbs/cosmosdb_account.tf
> +  local_authentication_disabled       = try(var.settings.local_authentication_disabled, false)
Changed

2023-07-03 07:05 UTC, arnaudlh approved these changes
LGTM

2023-07-03 07:06 UTC, arnaudlh commented on modules/databases/cosmos_dbs/cosmosdb_account.tf
> +  access_key_metadata_writes_enabled  = try(var.settings.access_key_metadata_writes_enabled, true)
mistakes from the past ;)

2023-07-03 07:06 UTC, arnaudlh commented
thanks for your contribution @mdanylyuk

2023-07-03 07:06 UTC, merged