Add powerbi embedded module
aztfmod/terraform-azurerm-caf pull request #1684
Opened 2023-07-03 10:23 UTC by kevindelmont

## PR Checklist

---

- [x] I have added example(s) inside the [./examples/] folder
- [x] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- [x] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [x] I have checked to ensure there aren't other open Pull Requests for the same update/change?

## Description

Add [powerbi embedded](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/website/docs/r/powerbi_embedded.html.markdown) module

## Does this introduce a breaking change

- [ ] YES
- [x] NO

## Testing

Use the example I provided

2023-07-11 03:06 UTC, arnaudlh commented
Thanks for your contribution @kevindelmont, your examples only creates a RG, I think you are missing a couple of variables declarations. Could you please update?  thanks

2023-07-11 07:28 UTC, kevindelmont commented on examples/powerbi_embedded/100-powerbi_embeded/configuration.tfvars
> +powerbi_embedded = {
Hi @arnaudlh, the example of creating the powerbi resource is already there.

2023-07-12 07:29 UTC, arnaudlh requested changes
@kevindelmont for the example to work, you will need to add ```powerbi_embedded = var.powerbi_embedded``` in /examples/module.tf and declare the variable also in /examples.

Please also use the data source instead of resource for name, to improve plan-time data, as suggested.

2023-07-12 07:29 UTC, arnaudlh commented on modules/powerbi_embedded/module.tf
> +resource "azurecaf_name" "powerbi" {
```suggestion
data "azurecaf_name" "powerbi" {
```

2023-07-12 07:29 UTC, arnaudlh commented on modules/powerbi_embedded/module.tf
> +  name                = azurecaf_name.powerbi.result
```suggestion
  name                = data.azurecaf_name.powerbi.result
```

2023-07-13 03:14 UTC, arnaudlh commented on examples/powerbi_embedded/100-powerbi_embeded/configuration.tfvars
> +powerbi_embedded = {
yes it is, but its not working :)

2023-07-17 08:27 UTC, kevindelmont commented on modules/powerbi_embedded/module.tf
> +  name                = azurecaf_name.powerbi.result
I updated

2023-07-18 09:36 UTC, arnaudlh approved these changes
LGTM

2023-07-18 09:41 UTC, arnaudlh commented
There seem to be a bug in the naming provider, I have filled https://github.com/aztfmod/terraform-provider-azurecaf/issues/248 to track it. In the meantime, the feature is still useable with a ```passthrough = true``` in the ```global_settings``` section.

2023-07-18 09:42 UTC, merged