Add ip_configuration block to private endpoints
aztfmod/terraform-azurerm-caf pull request #1691
Opened 2023-07-11 07:06 UTC by fschirinzi

# [Issue-id](https://github.com/aztfmod/terraform-azurerm-caf/issues/1689)

## PR Checklist

---

- [ ] I have added example(s) inside the [./examples/] folder
- [ ] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- [X] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [X] I have checked to ensure there aren't other open Pull Requests for the same update/change?

## Description

Currently, it is not possible to define a static IP-address for private endpoints by defining the `ip_configuration` block, which is supported in the [Private-Endpoint Terraform Resource >3.21.0](https://registry.terraform.io/providers/hashicorp/azurerm/3.21.0/docs/resources/private_endpoint#ip_configuration).
This PR enables reading the `ip_configuration` from the settings property.

## Does this introduce a breaking change

- [ ] YES
- [X] NO

## Testing

2023-07-26 07:26 UTC, arnaudlh requested changes
thanks for the PR @fschirinzi, are you able to add an self-contained example so we can run your code/examples in CI/CD?
thanks
Arnaud

2023-07-26 08:25 UTC, fschirinzi commented
@arnaudlh Hi Arnaud.
I updated the example. Does it work now?

2023-07-26 09:18 UTC, arnaudlh requested changes
hi @fschirinzi, 

I can see there that could be multiple ```ip_configuration``` blocks as per https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_endpoint#ip_configuration.

I think config file should be like that: 
```
        ip_configurations = {
          static1= {          
            name               = "kv01_rg1-name"
            private_ip_address = "10.150.100.140"
            subresource_name   = "vault"
            member_name        = "default"
          }
          static2 = {
            name               = "kv02_rg1-name"
            private_ip_address = "10.150.100.150"
          }
        }
```

and the code like: 

```
  dynamic "ip_configuration" {
    for_each = try(var.settings.ip_configurations, {})

...
```

Try and let me know if ok with it?

2023-07-26 12:46 UTC, fschirinzi commented
You are right. The `one or more` block was introduced in a later version than the one mentioned by me (3.21.0).
I missed, that the[ used version](https://github.com/aztfmod/terraform-azurerm-caf/blob/5e723aa6f48f5756dd9b5f2fb5f90e1ae16ff51a/main.tf#L6) is `3.56.0`.

I'll accept the changes.

2023-07-31 06:53 UTC, fschirinzi commented
@arnaudlh Should work now. Can you test please?

2023-08-03 09:00 UTC, arnaudlh approved these changes
LGTM

2023-08-03 09:00 UTC, arnaudlh commented on examples/networking/private_endpoint/README.md
> +sudo terraform plan -var-file examples/networking/private_endpoint/configuration.tfvars
```suggestion
 terraform plan -var-file examples/networking/private_endpoint/configuration.tfvars
```

2023-08-03 09:00 UTC, arnaudlh commented on examples/networking/private_endpoint/README.md
> +sudo terraform plan -var-file examples/networking/private_endpoint/configuration.tfvars
```suggestion
terraform plan -var-file examples/networking/private_endpoint/configuration.tfvars
```

2023-08-03 09:00 UTC, arnaudlh commented on examples/networking/private_endpoint/README.md
> +You can test this module outside of a landingzone using
```suggestion
You can test this module outside of a rover using
```

2023-08-03 09:09 UTC, merged