Add support for azure maps account
aztfmod/terraform-azurerm-caf pull request #1727
Opened 2023-07-27 08:37 UTC by reshmarajan1730

# [Issue-id](https://github.com/aztfmod/terraform-azurerm-caf/issues/ISSUE-ID-GOES-HERE)

## PR Checklist

---

- [ ] I have added example(s) inside the [./examples/] folder
- [ ] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- [ ] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [ ] I have checked to ensure there aren't other open Pull Requests for the same update/change?

## Description

## Does this introduce a breaking change

- [ ] YES
- [ ] NO

## Testing

2023-07-27 09:23 UTC, reshmarajan1730 commented
@LaurentLesle renamed to maps_accounts

2023-07-27 13:52 UTC, reshmarajan1730 commented
@arnaudlh could you please have a look

2023-07-28 04:47 UTC, arnaudlh requested changes
thanks for your PR @reshmarajan1730! 

please have a look at my suggestions and comments and also please add support for tags as it is support by the maps per: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/maps_account#tags

2023-07-28 04:47 UTC, arnaudlh commented on modules/maps/maps_account/maps_account.tf
> +resource "azurecaf_name" "map" {
```suggestion
data "azurecaf_name" "map" {
```

2023-07-28 04:47 UTC, arnaudlh commented on modules/maps/maps_account/maps_account.tf
> +  name                = azurecaf_name.map.result
```suggestion
  name                = data.azurecaf_name.map.result
```

2023-07-28 04:47 UTC, arnaudlh commented on examples/variables.tf
> -variable "storage_account_file_shares" {
Do not delete other variables, just add yours :) 

```
variable "storage_account_file_shares" {
  default     = {}
}

variable "maps_accounts" {
  default     = {}
}
```

2023-08-01 06:14 UTC, reshmarajan1730 commented on modules/maps/maps_account/maps_account.tf
> +resource "azurecaf_name" "map" {
updated

2023-08-01 06:14 UTC, reshmarajan1730 commented on modules/maps/maps_account/maps_account.tf
> +  name                = azurecaf_name.map.result
updated

2023-08-01 06:14 UTC, reshmarajan1730 commented on examples/variables.tf
> -variable "storage_account_file_shares" {
updated

2023-08-01 06:17 UTC, reshmarajan1730 commented
@arnaudlh I have updated the PR. With this update I have also added the feature to store the azure map account's primary and secondary access keys in a keyvault, if specified. This has also been tested.

2023-08-03 02:39 UTC, arnaudlh requested changes
thanks @reshmarajan1730, its looks nice and works on my environment. 

Are you able to:
1. run a ```terraform fmt``` on your files 
2. add path to your example in  ```standalone-scenarios.json``` so the CD/CI picks it. 

After that we should be ready for merge! 
Thanks.

2023-08-04 01:57 UTC, arnaudlh approved these changes
LGTM

2023-08-04 07:02 UTC, reshmarajan1730 commented
@arnaudlh I am not able to merge because of the branch protection

2023-08-04 08:48 UTC, arnaudlh commented
> @arnaudlh I am not able to merge because of the branch protection

no worries, I'm the one merging ;)

2023-08-05 04:07 UTC, merged