add container app module
aztfmod/terraform-azurerm-caf pull request #1792
Opened 2023-09-06 19:29 UTC by trapeznikov

# [1301](https://github.com/aztfmod/terraform-azurerm-caf/issues/1301)

## PR Checklist

---

- [x] I have added example(s) inside the [./examples/] folder
- [x] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- [x] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [x] I have checked to ensure there aren't other open Pull Requests for the same update/change?

## Description

## Does this introduce a breaking change

- [ ] YES
- [x] NO

## Testing

2023-09-07 01:17 UTC, arnaudlh requested changes
Thanks for the PR @trapeznikov, Im running examples and getting:

```
│ Error: Reference to undeclared input variable
│ 
│   on module.tf line 106, in module "example":
│  106:     container_app                         = var.container_app
│ 
│ An input variable with the name "container_app" has not been declared. This variable can be declared with a variable
│ "container_app" {} block.
╵
╷
│ Error: Reference to undeclared input variable
│ 
│   on module.tf line 107, in module "example":
│  107:     container_app_dapr_component          = var.container_app_dapr_component
│ 
│ An input variable with the name "container_app_dapr_component" has not been declared. This variable can be declared with
│ a variable "container_app_dapr_component" {} block.
╵
╷
│ Error: Reference to undeclared input variable
│ 
│   on module.tf line 108, in module "example":
│  108:     container_app_environment             = var.container_app_environment
│ 
│ An input variable with the name "container_app_environment" has not been declared. This variable can be declared with a
│ variable "container_app_environment" {} block.
╵
╷
│ Error: Reference to undeclared input variable
│ 
│   on module.tf line 109, in module "example":
│  109:     container_app_environment_certificate = var.container_app_environment_certificate
│ 
│ An input variable with the name "container_app_environment_certificate" has not been declared. This variable can be
│ declared with a variable "container_app_environment_certificate" {} block.
╵
╷
│ Error: Reference to undeclared input variable
│ 
│   on module.tf line 110, in module "example":
│  110:     container_app_environment_storage     = var.container_app_environment_storage
│ 
│ An input variable with the name "container_app_environment_storage" has not been declared. This variable can be declared
│ with a variable "container_app_environment_storage" {} block.
╵
Terraform plan return code: 1
Error 1 on or near line 57: Error running terraform plan; exiting with status 1
```

2023-09-07 14:46 UTC, trapeznikov commented
@arnaudlh need to add container_app to https://github.com/Azure/caf-terraform-landingzones/tree/main/caf_solution. What's the process of adding a new feature to these 2 repos? Should the change first go to `caf-terraform-landingzones`?

2023-09-08 01:02 UTC, arnaudlh commented
> @arnaudlh need to add container_app to https://github.com/Azure/caf-terraform-landingzones/tree/main/caf_solution. What's the process of adding a new feature to these 2 repos? Should the change first go to `caf-terraform-landingzones`?

1. update the module with examples working, so people can leverage it as standalone
2. update the azure repo with the new var names and module version constraint.

2023-09-09 00:44 UTC, trapeznikov commented
@arnaudlh fixed the variables file in the example module, it should run fine now. Sorry for the confusion, I was just testing it differently.

2023-10-24 11:47 UTC, mresetar-croz commented
I am currently working with this PR code. I hope it gets merged soon. Maybe not the right place but please follow https://github.com/hashicorp/terraform-provider-azurerm/issues/21747 as workload profiles support is something in the future that should be supported by CAF as well.

2023-11-01 08:21 UTC, jvdhaterdwestland commented on examples/module.tf
> +    container_app_environment_storage     = var.container_app_environment_storage
Currently all container_app related are in singular form, this should be plural.

2023-11-01 08:29 UTC, jvdhaterd commented on locals.tf
> +    container_groups                      = try(var.compute.container_groups, {})
Imho the container_app related should be in a plural form, matching the rest.

2023-11-01 17:53 UTC, trapeznikov commented on locals.tf
> +    container_groups                      = try(var.compute.container_groups, {})
Thanks for your feedback, I will fix it.

2023-11-01 20:56 UTC, trapeznikov commented on modules/compute/container_app/container_app.tf
> +  template {
@chatelain-io added support for scale rules.

2023-11-02 17:24 UTC, trapeznikov commented
@arnaudlh I resolved all the comment and rebased the branch. Can you please review?

2023-11-03 08:55 UTC, jvdhaterd approved these changes

2023-11-22 16:26 UTC, trapeznikov commented
@arnaudlh @LaurentLesle can you please review this PR?

2023-11-23 07:06 UTC, iriahk89 commented on modules/compute/container_app_environment/container_app_environment.tf
> +  tags                           = merge(local.tags, try(var.settings.tags, null))
please help to add support for another 2 parameter: dapr_application_insights_connection_string & zone_redundancy_enabled

2023-11-23 07:08 UTC, iriahk89 requested changes
@trapeznikov I reviewed the PR and would really appreciate if you could add those 2 features and resolve the minor bug as one of my customers also waiting for this resource. Let me know if you need helps. Thanks!

2023-11-23 07:20 UTC, arnaudlh commented on modules/compute/container_app_environment/container_app_environment.tf
> +  tags                           = merge(local.tags, try(var.settings.tags, null))
@trapeznikov good PR - thank you! if you dont mind adding the 2 attributes mentionned by @iriahk89, I think we are good to go!

2023-11-23 07:22 UTC, iriahk89 commented
@trapeznikov I reviewed the PR and would really appreciate if you could add those 2 features and resolve the minor bug as one of my customers also waiting for this resource. Let me know if you need helps. Thanks!

2023-11-23 20:01 UTC, trapeznikov commented on modules/compute/container_app_environment/container_app_environment.tf
> +  tags                           = merge(local.tags, try(var.settings.tags, null))
@arnaudlh @iriahk89 done. Please review.

2023-11-24 01:01 UTC, iriahk89 approved these changes
LGTM. we can add the integration with app insight combined object later for dapr_application_insights_connection_string if needed

2023-11-24 01:14 UTC, arnaudlh approved these changes
LGTM

2023-11-24 01:32 UTC, merged

2023-11-24 01:33 UTC, arnaudlh commented
thanks for your contribution @trapeznikov   and for your reviews @iriahk89 @jvdhaterd