Add az auth to postgres flexible
aztfmod/terraform-azurerm-caf pull request #1801
Opened 2023-09-19 01:15 UTC by isevenbe

# [1800](https://github.com/aztfmod/terraform-azurerm-caf/issues/1800)

## PR Checklist

---

- [X] I have added example(s) inside the [./examples/postgresql_flexible_server/103-simple-postgresql-flexible-with-az-auth/configuration.tfvars] folder
- [ ] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- [X] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [X] I have checked to ensure there aren't other open Pull Requests for the same update/change?

## Description

Adding the support of authentication block inside the azurerm_postgresql_flexible_server module ref: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_flexible_server#authentication

## Does this introduce a breaking change

- [ ] YES
- [X] NO

2023-09-20 02:04 UTC, arnaudlh requested changes
Please review.

2023-09-20 02:04 UTC, arnaudlh commented on modules/databases/postgresql_flexible_server/server.tf
> +    active_directory_auth_enabled = try(var.settings.authentication.active_directory_auth_enabled, false)
```suggestion
    active_directory_auth_enabled = try(var.settings.authentication.active_directory_auth_enabled, null)
```

2023-09-20 02:04 UTC, arnaudlh commented on modules/databases/postgresql_flexible_server/server.tf
> +    password_auth_enabled         = try(var.settings.authentication.password_auth_enabled, true)
```suggestion
    password_auth_enabled         = try(var.settings.authentication.password_auth_enabled, null)
```

2023-09-20 02:04 UTC, arnaudlh commented on modules/databases/postgresql_flexible_server/server.tf
> +    tenant_id                     = try(var.settings.authentication.tenant_id, "")
Can we add the current ```tenant_id``` from vars if none is specified?

2023-09-20 02:04 UTC, arnaudlh commented on modules/databases/postgresql_flexible_server/server.tf
> +  authentication {
should be optional block (see pattern in other parts of the code)

2023-09-20 05:08 UTC, isevenbe commented on modules/databases/postgresql_flexible_server/server.tf
> +    tenant_id                     = try(var.settings.authentication.tenant_id, "")
I don't gezt what do you mean, have you an example that could help me to understand ? :)

2023-09-20 05:09 UTC, isevenbe commented
@arnaudlh i have reviewed

2023-09-21 02:42 UTC, arnaudlh commented on modules/databases/postgresql_flexible_server/server.tf
> +    tenant_id                     = try(var.settings.authentication.tenant_id, "")
Thinking about something like this:

```
tenant_id = can(var.settings.authentication.tenant_id) ? var.settings.authentication.tenant_id : var.client_config.tenant_id
```

And alongside, comment ```tenant_id``` in the example the tenant_id, so it passes CI/CD.

2023-09-21 07:08 UTC, isevenbe commented on modules/databases/postgresql_flexible_server/server.tf
> +    tenant_id                     = try(var.settings.authentication.tenant_id, "")
Ok i get it !

2023-09-26 13:41 UTC, ALA-DQ commented
Up, I need this feature as well, asap, for my company.

2023-09-29 09:10 UTC, arnaudlh commented on examples/postgresql_flexible_server/103-simple-postgresql-flexible-with-az-auth/configuration.tfvars
> +      tenant_id = "00000-ee35-4265-95f6-46e9a9b4ec96"
```suggestion
      #tenant_id = "00000-ee35-4265-95f6-46e9a9b4ec96"
```

2023-09-29 09:46 UTC, arnaudlh approved these changes
LGTM

2023-09-29 09:46 UTC, arnaudlh commented
thanks for your contribution @isevenbe!

2023-09-29 09:47 UTC, merged