Add Maintenance Configuration module
aztfmod/terraform-azurerm-caf pull request #1870
Opened 2023-11-23 14:17 UTC by kevindelmont

## PR Checklist

---

- [x] I have added example(s) inside the [./examples/] folder
- [x] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- [x] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [x] I have checked to ensure there aren't other open Pull Requests for the same update/change?

## Description

Add Manages a maintenance configuration module

## Does this introduce a breaking change

- [ ] YES
- [x] NO

## Testing

2024-01-05 09:56 UTC, kevindelmont commented
@arnaudlh can you please take a look at this PR?

2024-01-08 06:00 UTC, arnaudlh commented
> @arnaudlh can you please take a look at this PR?

thanks @kevindelmont - running examples, I'm getting: 
```
╷
│ Error: Unsupported attribute
│ 
│   on ../modules/maintenance/configuration/module.tf line 22, in resource "azurerm_maintenance_configuration" "maintenance_configuration":
│   22:     for_each = var.settings.window != null ? [var.settings.window] : []
│     ├────────────────
│     │ var.settings is object with 4 attributes
│ 
│ This object does not have an attribute named "window".
╵```

2024-01-08 06:32 UTC, arnaudlh requested changes
thanks for the PR @kevindelmont, please review the suggestion to make it work for windows. can you please add support/example for linux vm? thanks

2024-01-08 06:32 UTC, arnaudlh commented on modules/maintenance/configuration/module.tf
> +    for_each = var.settings.window != null ? [var.settings.window] : []
```suggestion
    for_each = try(var.settings.window, null) != null ? [var.settings.window] : []
```

2024-01-08 06:32 UTC, arnaudlh commented on examples/maintenance_configuration/200-maintenance-configuration-assignment-vm/configuration.tfvars
> +    boot_diagnostics_storage_account_key = "bootdiag_region1"
```suggestion
```

2024-01-08 06:32 UTC, arnaudlh commented on examples/maintenance_configuration/200-maintenance-configuration-assignment-vm/configuration.tfvars
> +        bypassPlatformChecksOnUserSchedule = true
```suggestion
        bypass_platform_safety_checks_on_user_schedule_enabled = true
```

2024-01-08 06:32 UTC, arnaudlh commented on modules/compute/virtual_machine/vm_windows.tf
> +  bypass_platform_safety_checks_on_user_schedule_enabled = try(each.value.bypass_platform_safety_checks_on_user_schedule_enabled, false)
```suggestion
  bypass_platform_safety_checks_on_user_schedule_enabled = try(each.value.bypass_platform_safety_checks_on_user_schedule_enabled, null)
```

2024-01-08 08:45 UTC, kevindelmont commented on modules/maintenance/configuration/module.tf
> +    for_each = var.settings.window != null ? [var.settings.window] : []
I added example for linux vm and fixed the maintenance configuration module.
Thanks for your suggestions.

2024-01-08 08:46 UTC, kevindelmont commented on examples/maintenance_configuration/200-maintenance-configuration-assignment-vm/configuration.tfvars
> +    boot_diagnostics_storage_account_key = "bootdiag_region1"
Thanks

2024-01-08 10:16 UTC, merged