docs: add notice and remove MSFT refs
aztfmod/terraform-azurerm-caf pull request #1914
Opened 2024-01-26 08:19 UTC by matt-FFFFFF

2024-01-31 03:17 UTC, LaurentLesle requested changes
See comment on code of conduct

2024-01-31 03:17 UTC, LaurentLesle commented on README.md
> -This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/).
what's the reason?

2024-03-15 03:13 UTC, arnaudlh approved these changes

2024-03-15 03:14 UTC, arnaudlh commented on README.md
> -This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/).
No response :)

2024-03-15 03:14 UTC, merged