Add storage defender support
aztfmod/terraform-azurerm-caf pull request #2030
Opened 2024-07-02 14:46 UTC by shanoor

## PR Checklist

---

- [ ] I have added example(s) inside the [./examples/] folder
- [ ] I have added the example(s) to the integration test list for [normal (~30 minutes)](./workflows/standalone-scenarios.json) or [long runner >30 minutes](./workflows/standalone-scenarios-longrunners.json)
- [x] I have checked the [coding conventions as per the wiki](https://github.com/aztfmod/terraform-azurerm-caf/wiki)
- [x] I have checked to ensure there aren't other open Pull Requests for the same update/change?

## Description

Add support for enabling Defender for Storage on a storage account.

## Does this introduce a breaking change

- [ ] YES
- [x] NO

## Testing

2024-07-04 06:16 UTC, arnaudlh requested changes
Thanks for the PR @shanoor, are you able to change it to default the values to the provider instead of the module? 
Can you please also add an example and the CI/CD line?

2024-07-04 06:16 UTC, arnaudlh commented on modules/storage_account/storage_defender.tf
> +  override_subscription_settings_enabled      = try(var.storage_account.defender.override_subscription_settings, false)
```suggestion
  override_subscription_settings_enabled      = try(var.storage_account.defender.override_subscription_settings, null)
```

2024-07-04 06:16 UTC, arnaudlh commented on modules/storage_account/storage_defender.tf
> +  malware_scanning_on_upload_enabled          = try(var.storage_account.defender.malware_scanning_on_upload, false)
```suggestion
  malware_scanning_on_upload_enabled          = try(var.storage_account.defender.malware_scanning_on_upload, null)
```

2024-07-04 06:16 UTC, arnaudlh commented on modules/storage_account/storage_defender.tf
> +  malware_scanning_on_upload_cap_gb_per_month = try(var.storage_account.defender.malware_scanning_on_upload_cap_gb_per_month, -1)
```suggestion
  malware_scanning_on_upload_cap_gb_per_month = try(var.storage_account.defender.malware_scanning_on_upload_cap_gb_per_month, null)
```

2024-07-04 06:16 UTC, arnaudlh commented on modules/storage_account/storage_defender.tf
> +  sensitive_data_discovery_enabled            = try(var.storage_account.defender.sensitive_data_discovery_enabled, false)
```suggestion
  sensitive_data_discovery_enabled            = try(var.storage_account.defender.sensitive_data_discovery_enabled, null)
```

2024-07-05 12:54 UTC, shanoor commented
> Thanks for the PR @shanoor, are you able to change it to default the values to the provider instead of the module? Can you please also add an example and the CI/CD line?

I committed your suggestions and added an example.

2024-07-23 05:59 UTC, arnaudlh approved these changes
lgtm

2024-07-23 06:00 UTC, merged