Hn aks addons
aztfmod/terraform-azurerm-caf pull request #230
Opened 2021-01-18 10:08 UTC by hieumoscow

Support all properties from https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster

Support Log analytics keys for oms_agents addons

2021-01-25 10:32 UTC, LaurentLesle requested changes
Very good PR. On change to review

2021-01-25 10:32 UTC, LaurentLesle commented on modules/compute/aks/aks.tf
> +              object_id                 = oms_agent_identity.valueclient_id
can you check:
```hcl
object_id                 = oms_agent_identity.valueclient_id
```

2021-01-25 14:41 UTC, hieumoscow commented on modules/compute/aks/aks.tf
> +              object_id                 = oms_agent_identity.valueclient_id
Modified

2021-01-26 01:52 UTC, LaurentLesle approved these changes

2021-01-26 01:53 UTC, merged