Adding first implementation for Azure Netapp Files and NFSv3
aztfmod/terraform-azurerm-caf pull request #235
Opened 2021-01-25 12:34 UTC by xpillons

closing #226

2021-01-26 09:28 UTC, LaurentLesle requested changes
@xpillons thanks a lot for the PR. Very good. Can I ask you to add the example scenario into the .github/workflows/master-100.yaml . The CI will then execute it.

2021-01-26 09:56 UTC, xpillons commented
@LaurentLesle I've added netapp in the workflow. however there were a conflict inthe workflow file so I've merge the master into my branch.

2021-01-28 06:19 UTC, arnaudlh approved these changes

2021-01-28 11:03 UTC, LaurentLesle approved these changes

2021-01-28 11:03 UTC, merged