Js encrypt disk cmk
aztfmod/terraform-azurerm-caf pull request #296
Opened 2021-02-26 02:48 UTC by jorseng

Added disk_encryption_set module
Added access policy support for disk_encryption_set
Added support for vm os_disk with disk_encryption_set_id

2021-03-02 05:54 UTC, arnaudlh requested changes
good contribution @jorseng can you please add examples and CI examples?

2021-03-03 10:29 UTC, jorseng commented
> good contribution @jorseng can you please add examples and CI examples?

I have added configuration example to directory examples> virtual_machine > 212-vm-disk-encryption-set

2021-03-03 12:39 UTC, anamikanayal01 commented
@arnaudlh @jorseng  just updated the branch with Disk encryption set creation and assignment for os_disk and data_disk ; example folder 105 >Standalone for windows. I am working on the Linux VM so please dont approve the PR yet till i complete for linux vm.

2021-03-25 03:46 UTC, arnaudlh approved these changes

2021-03-25 03:51 UTC, merged