adding GitLab CAF Module
aztfmod/terraform-azurerm-caf pull request #332
Opened 2021-03-11 19:38 UTC by polatengin

Adding GitLab terraform provider project creation [resource](https://registry.terraform.io/providers/gitlabhq/gitlab/latest/docs) extension to CAF.

Verified the module by creating couple of new projects by following the below steps;

```bash
export environment=demo
export GITLAB_TOKEN=<token created at gitlab.com / or gitlab server>
# run the following command if you're using gitlab server
export GITLAB_BASE_URL=<url of the gitlab server>

rover -lz /tf/caf/public/landingzones/caf_launchpad -launchpad -var-folder /tf/caf/configuration/${environment}/level0/launchpad -parallelism 30 -level level0 -env demo -a apply

rover -lz /tf/modules/examples/ -var-folder /tf/modules/examples/devops/providers/gitlab/new_project/  -level level1 -env demo -a apply
```

After it finish running (it may take couple of minutes) you'll see couple of projects in your gitlab instance;

![image](https://user-images.githubusercontent.com/118744/110842576-55340d00-82b8-11eb-862c-593e4e7e9153.png)

_PS : I used the following configuration;_

```terraform
gitlab_projects = {

  test_project  = {
    name        = "test_project_2"
    description = "updated test project description"
    visibility  = "private"
  }

  demo_project  = {
    name        = "test_project_3"
    description = "test project description"
    visibility  = "private"
  }

}
```

2021-03-11 19:58 UTC, hattan commented on examples/devops/providers/gitlab/new_project/configuration.tfvars
> +    name = "ado_test"
We should rename this to gitlab_test. Do we need the RG here?

2021-03-11 19:58 UTC, hattan commented on modules/devops/providers/gitlab/README.md
> +# GitLab
We should add a note to the README that mentions that before running the module folks need to set GITLAB_TOKEN env variables.

And if they are using a GitLab server then they also need GITLAB_BASE_URL.

It might also be a good idea to add the example gitlab_project.tfvars to the readme.

2021-03-11 19:58 UTC, hattan commented on modules/devops/providers/gitlab/README.md
> +| gitlab\_token | Client configuration object (see module README.md). | `any` | n/a | yes |
We can remove the gitlab_token input since it's no longer a variable.

2021-03-11 19:58 UTC, hattan commented on modules/devops/providers/gitlab/README.md
> +# GitLab
We should also document the inputs accepted by the model in the readme, since currently we only support name, description and visibility.

  demo_project  = {
    name        = "demo_project_21"
    description = "This is a demo!"
    visibility  = "private"
  }

2021-03-11 20:08 UTC, polatengin commented on examples/devops/providers/gitlab/new_project/configuration.tfvars
> +    name = "ado_test"
yeah, removed the unneeded resource group, thanks

2021-03-11 20:10 UTC, polatengin commented on modules/devops/providers/gitlab/README.md
> +| gitlab\_token | Client configuration object (see module README.md). | `any` | n/a | yes |
👍

2021-03-12 19:20 UTC, rguthriemsft requested changes

2021-03-12 19:20 UTC, rguthriemsft commented on .github/workflows/master-100.yaml
> +  GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
@LaurentLesle do we need to do this?  Not sure what the right PR flow is for add-on PRs.

2021-03-12 19:20 UTC, rguthriemsft commented on modules/devops/providers/gitlab/README.md
> +# GitLab
Need to confirm what right approach is to CI validation for add-ons with CAF team.

2021-04-09 12:56 UTC, polatengin commented
decided to move gitlab caf module to [aztfmod/terraform-addons-caf](https://github.com/aztfmod/terraform-addons-caf) repo

PR for that is merged (https://github.com/aztfmod/terraform-addons-caf/pull/1)

2021-04-09 12:56 UTC, closed without merging