mssql_database short and long term retention policy support
aztfmod/terraform-azurerm-caf pull request #384
Opened 2021-04-15 15:04 UTC by jorseng

2021-04-20 01:29 UTC, LaurentLesle requested changes
Can you add this new example in the pipelines? https://github.com/aztfmod/terraform-azurerm-caf/blob/sqldb-retention-policy/.github/workflows/master-100-tf14.yaml

2021-04-20 01:40 UTC, arnaudlh commented
> Can you add this new example in the pipelines? https://github.com/aztfmod/terraform-azurerm-caf/blob/sqldb-retention-policy/.github/workflows/master-100-tf14.yaml

Hi @jorseng i added the pipelines, please include them next time ;)

2021-04-20 01:45 UTC, jorseng commented
> > Can you add this new example in the pipelines? https://github.com/aztfmod/terraform-azurerm-caf/blob/sqldb-retention-policy/.github/workflows/master-100-tf14.yaml
> 
> Hi @jorseng i added the pipelines, please include them next time ;)

Thanks @arnaudlh, i will remember for future examples

2021-04-28 00:23 UTC, arnaudlh approved these changes

2021-04-28 00:24 UTC, merged