Added feature for Web Application Firewal and link it to AGW and its listener
aztfmod/terraform-azurerm-caf pull request #390
Opened 2021-04-19 03:54 UTC by iriahk89

resolve #353

2021-04-20 01:14 UTC, arnaudlh commented
@iriahk89 can you please review and make sure its in the example and in caf solution lz? 

From the CI run, looks like var declaration is missing to execute the scenario: 
```
The root module does not declare a variable named
"application_gateway_waf_policies" but a value was found in file
"/__w/terraform-azurerm-caf/terraform-azurerm-caf/examples/app_gateway/102-waf-policy/waf.tfvars".
To use this value, add a "variable" block to the configuration.
```
thanks

2021-04-20 01:20 UTC, LaurentLesle requested changes
Added view comments. Thanks @iriahk89

2021-04-20 01:20 UTC, LaurentLesle commented on modules/networking/application_gateway/application_gateway.tf
> -  firewall_policy_id = try(var.settings.firewall_policy_id, null)
can you keep the firewall_policy_id for backward compatibility?

2021-04-20 01:20 UTC, LaurentLesle commented on examples/app_gateway/102-waf-policy/waf.tfvars
> +application_gateway_waf_policies = {
Try to have an example that covers all the blocks in the implementation. At least the public example https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/web_application_firewall_policy#example-usage

2021-04-20 05:24 UTC, iriahk89 commented on modules/networking/application_gateway/application_gateway.tf
> -  firewall_policy_id = try(var.settings.firewall_policy_id, null)
Fixed

2021-04-20 05:25 UTC, iriahk89 commented on examples/app_gateway/102-waf-policy/waf.tfvars
> +application_gateway_waf_policies = {
Updated examples as advised

2021-04-21 06:06 UTC, LaurentLesle approved these changes

2021-04-21 06:06 UTC, merged