Add support for Redis Cache VNET integration
aztfmod/terraform-azurerm-caf pull request #404
Opened 2021-04-23 14:34 UTC by v4ld3r5

This PR solves #402, adds support to create a fully private Redis Cache:
* Adds `public_network_access_enabled` parameter to module's interface
* Sets new module variable to pass the `subnet.id` directly, instead of part of `redis` map, to be able to obtain it dynamically from a landing zone
* Add `subnet_id` parameter from top module and construct the lookup from `combined_objects`
* Depend on networking module for ordering purposes

This code has been tested and I'm able to successfully deploy a Premium instance within vnet.

2021-04-27 10:16 UTC, LaurentLesle requested changes
Thanks for the PR. I put some comments that are consistent across the 3 PR you have sumbitted.

Add an example here - https://github.com/aztfmod/terraform-azurerm-caf/tree/master/examples/redis_cache

Reference the example in the pipelines https://github.com/aztfmod/terraform-azurerm-caf/tree/master/.github/workflows

2021-04-27 10:16 UTC, LaurentLesle commented on redis_caches.tf
> +  subnet_id           = try(each.value.subnet_key, null) == null ? null : try(local.combined_objects_networking[local.client_config.landingzone_key][each.value.vnet_key].subnets[each.value.subnet_key
USe the simplified structure

2021-04-29 09:05 UTC, v4ld3r5 commented on redis_caches.tf
> +  subnet_id           = try(each.value.subnet_key, null) == null ? null : try(local.combined_objects_networking[local.client_config.landingzone_key][each.value.vnet_key].subnets[each.value.subnet_key
Hi @LaurentLesle , please find the additional commit with the example and reference

Br

2021-04-29 09:28 UTC, v4ld3r5 commented on redis_caches.tf
> +  subnet_id           = try(each.value.subnet_key, null) == null ? null : try(local.combined_objects_networking[local.client_config.landingzone_key][each.value.vnet_key].subnets[each.value.subnet_key
> USe the simplified structure

Is there a more simpler way? I couldn't find it in the codebase. Do you mind giving an example?

2021-04-30 10:19 UTC, LaurentLesle commented on redis_caches.tf
> +  subnet_id           = try(each.value.subnet_key, null) == null ? null : try(local.combined_objects_networking[local.client_config.landingzone_key][each.value.vnet_key].subnets[each.value.subnet_key
I was referring to the following:

`subnet_id = try(local.combined_objects_networking[try(each.value.lz_key, local.client_config.landingzone_key)][each.value.vnet_key].subnets[each.value.subnet_key].id, null)` 

Try and if it works you that in the other PR you have submitted

2021-05-01 20:53 UTC, v4ld3r5 commented on redis_caches.tf
> +  subnet_id           = try(each.value.subnet_key, null) == null ? null : try(local.combined_objects_networking[local.client_config.landingzone_key][each.value.vnet_key].subnets[each.value.subnet_key
Thx got it, updated

2021-05-03 08:39 UTC, v4ld3r5 reviewed
Corrected example folder name, added pipeline links

2021-05-04 05:27 UTC, merged