Feature/lighthouse
aztfmod/terraform-azurerm-caf pull request #410
Opened 2021-04-27 05:41 UTC by papunsenapati07

Added Light House module and example

2021-04-27 10:02 UTC, LaurentLesle requested changes
Thanks @papunsenapati07 . Good contribution. I have added some review to address before we can merge

2021-04-27 10:02 UTC, LaurentLesle commented on examples/lighthouse/100-lighthouse-simple/configuration.tfvars
> +          id     = "8833edce-0f1d-4948-ac11-161be573d7f7" # Group id eg: 8833edce-0f1d-4948-ac11-161be573d7f7
remove the guid or put some fake guid

2021-04-27 10:02 UTC, LaurentLesle commented on examples/lighthouse/100-lighthouse-simple/configuration.tfvars
> +        id     = "/subscriptions/06abbca2-ec1f-4a7f-9d2c-20355a1ffabe" #
remove the guid or put some fake guid

2021-04-27 10:02 UTC, LaurentLesle commented on examples/lighthouse/100-lighthouse-simple/configuration.tfvars
> +      id     = "/subscriptions/06abbca2-ec1f-4a7f-9d2c-20355a1ffabe" # The ID of the managed subscription.
remove the guid or put some fake guid

2021-04-27 10:02 UTC, LaurentLesle commented on examples/lighthouse/100-lighthouse-simple/configuration.tfvars
> +    managing_tenant_id = "3217d691-edcd-490d-b5ec-dc724087b782" # The ID of the managing tenant
remove the guid or put some fake guid

2021-04-28 02:59 UTC, papunsenapati07 commented on modules/security/lighthouse_definition/assignment.tf
> +  count = try(coalesce(
I kept it count to just do a null validation, the subscription scope dosen't have list of objects instead it will only have one element.

2021-04-28 02:59 UTC, papunsenapati07 commented on examples/lighthouse/100-lighthouse-simple/configuration.tfvars
> +          id     = "8833edce-0f1d-4948-ac11-161be573d7f7" # Group id eg: 8833edce-0f1d-4948-ac11-161be573d7f7
added fake guid

2021-04-28 03:01 UTC, papunsenapati07 commented on examples/lighthouse/100-lighthouse-simple/configuration.tfvars
> +      id     = "/subscriptions/06abbca2-ec1f-4a7f-9d2c-20355a1ffabe" # The ID of the managed subscription.
added fake guid

2021-04-28 03:04 UTC, papunsenapati07 commented on examples/lighthouse/100-lighthouse-simple/configuration.tfvars
> +        id     = "/subscriptions/06abbca2-ec1f-4a7f-9d2c-20355a1ffabe" #
added fake guid

2021-04-28 03:04 UTC, papunsenapati07 commented on examples/lighthouse/100-lighthouse-simple/configuration.tfvars
> +    managing_tenant_id = "3217d691-edcd-490d-b5ec-dc724087b782" # The ID of the managing tenant
added fake guid

2021-04-29 09:07 UTC, LaurentLesle approved these changes
Great contribution

2021-04-29 09:08 UTC, merged