enhancement for app gateway added ssl_policy
aztfmod/terraform-azurerm-caf pull request #509
Opened 2021-06-09 10:47 UTC by papunsenapati07

2021-06-09 10:51 UTC, arnaudlh commented on modules/networking/application_gateway/application_gateway.tf
> +      policy_type          = var.settings.ssl_policy.policy_type
hi @papunsenapati07 can you add the attribute disabled_protocols as per doc.

2021-06-09 10:53 UTC, arnaudlh commented on modules/networking/application_gateway/application_gateway.tf
> +    for_each = try(var.settings.ssl_policy, [])
since its A block, can you please implement this with the feature flag pattern? 
```
for_each = try(var.settings.ssl_policy, null) == null ? [] : [1] 
```

2021-06-09 10:54 UTC, arnaudlh commented on modules/networking/application_gateway/application_gateway.tf
> +      policy_name          = var.settings.ssl_policy.policy_name
policy_name should optional as per doc

2021-06-09 10:54 UTC, arnaudlh requested changes
thanks for your PR @papunsenapati07 can you please review the proposed changes? thanks!

2021-06-09 10:55 UTC, arnaudlh commented on modules/networking/application_gateway/application_gateway.tf
> +      policy_type          = var.settings.ssl_policy.policy_type
optional also

2021-06-09 11:00 UTC, papunsenapati07 commented on modules/networking/application_gateway/application_gateway.tf
> +    for_each = try(var.settings.ssl_policy, [])
Thanks @arnaudlh I did that and reverted back before committing.

2021-06-10 02:39 UTC, arnaudlh approved these changes

2021-06-10 02:55 UTC, merged