Support remote rg lz referencing
aztfmod/terraform-azurerm-caf pull request #636
Opened 2021-08-17 05:17 UTC by seanlok

Current Storage account only can use the RG that is created within the same tfstate only. Adding support for remote lz_key and key in order to be able to deploy to remote RG if required.

2021-08-25 04:21 UTC, LaurentLesle requested changes

2021-08-25 04:21 UTC, LaurentLesle commented on storage_accounts.tf
> +  resource_group_name = local.combined_objects_resource_groups[try(each.value.resource_group.lz_key, local.client_config.landingzone_key)][try(each.value.resource_group.key, each.value.resource_group
can you refactor with a coalesce to make it more readable

2021-08-25 04:21 UTC, LaurentLesle commented on storage_accounts.tf
> +  location            = lookup(each.value, "region", null) == null ? local.combined_objects_resource_groups[try(each.value.resource_group.lz_key, local.client_config.landingzone_key)][try(each.value.
same comment here with coalesce

2021-08-25 04:21 UTC, LaurentLesle commented on storage_accounts.tf
> +  base_tags           = try(local.global_settings.inherit_tags, false) ? local.combined_objects_resource_groups[try(each.value.resource_group.lz_key, local.client_config.landingzone_key)][try(each.va
and here

2021-08-31 18:12 UTC, arnaudlh requested changes
hi @seanlok, couple of things:
- coalese or coalesce? :) 
- couple of syntax errors
can you please review, test locally and update? thanks

2021-09-07 10:10 UTC, seanlok commented
This s fixed and tested.

2021-09-14 08:33 UTC, arnaudlh approved these changes

2021-09-14 08:33 UTC, merged

2021-09-14 08:34 UTC, arnaudlh commented
@seanlok - thank you for your contribution to Cloud Adoption Framework for Azure!