Adding virtual machine custom script extension
aztfmod/terraform-azurerm-caf pull request #760
Opened 2021-10-28 09:10 UTC by dimitrifc

Added virtual machine custom script extension according to #514

Module supports using managed or system identity for downloading files https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-windows

Follow up to https://github.com/aztfmod/terraform-azurerm-caf/pull/740:

- Added ability to reference storage account for fileuris by using key/landing zone key
- Added example

storageaccountname and storageaccountkey attributes are not implemented

2021-11-03 08:02 UTC, arnaudlh requested changes

2021-11-12 14:35 UTC, dimitrifc commented
Added module to examples/vm_extensions.tf for testing. Tested and fixed example.

2021-11-23 01:24 UTC, LaurentLesle approved these changes
Thanks @dimitrifc.

2021-11-23 05:35 UTC, merged

2021-11-23 05:35 UTC, arnaudlh reviewed
LGTM