Update output.tf
aztfmod/terraform-azurerm-caf pull request #773
Opened 2021-11-02 14:06 UTC by enricomitri

Added useful output definitions to retrieve the server which has the database installed

2021-11-03 04:15 UTC, arnaudlh requested changes

2021-11-03 04:15 UTC, arnaudlh commented on modules/databases/mssql_database/output.tf
> +  value = "${var.server_name}"
Feels a bit 2018 isnt it? :)

2021-11-04 10:40 UTC, enricomitri commented on modules/databases/mssql_database/output.tf
> +  value = "${var.server_name}"
Hi Arnaud,
thanks for your reply. I don't understand what you're asking, do you have an alternative solution?
Sorry this is my first terraform modules experience :)

2021-11-05 03:07 UTC, arnaudlh commented on modules/databases/mssql_database/output.tf
> +  value = "${var.server_name}"
hi @enricomitri, no problem we are all here learning! usually ```"${var.server_name}"``` is the Terraform former variables interpolation, nowadays we would simply ```var.server_name```

2021-11-05 12:19 UTC, enricomitri commented on modules/databases/mssql_database/output.tf
> +  value = "${var.server_name}"
Hi @arnaudlh, sure thanks for your explanation! I changed the definition as suggested. Let me know if it's ok

2021-11-10 00:53 UTC, LaurentLesle approved these changes
Thanks @enricomitri  for your first contribution

2021-11-10 05:44 UTC, arnaudlh approved these changes

2021-11-10 05:44 UTC, merged