Enhance vmss
aztfmod/terraform-azurerm-caf pull request #787
Opened 2021-11-12 07:45 UTC by dimitrifc

2021-11-16 11:36 UTC, arnaudlh requested changes

2021-11-16 11:36 UTC, arnaudlh commented on modules/compute/virtual_machine_scale_set/vmss_windows.tf
> +  timezone                     = try(each.value.timezone, null)
hi @dimitrifc isnt it applicable for linux vmss also?

2021-11-16 16:52 UTC, dimitrifc commented on modules/compute/virtual_machine_scale_set/vmss_windows.tf
> +  timezone                     = try(each.value.timezone, null)
Hi, the terraform module azurerm_linux_virtual_machine_scale_set does not support this property while the windows equivalent does. I don't remember ever needing this setting for Linux VMs either.

2021-11-17 05:13 UTC, arnaudlh approved these changes
LGTM

2021-11-17 05:13 UTC, merged