Add monitor_autoscale_setting(s) module
aztfmod/terraform-azurerm-caf pull request #803
Opened 2021-11-17 09:37 UTC by hyperfocus1337

Adding support for the [azurerm_monitor_autoscale_setting](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_autoscale_setting) resource.

Was able to make it work without inclusion of the [azurecaf_name](https://registry.terraform.io/providers/aztfmod/azurecaf/latest/docs/resources/azurecaf_name) resource, as it apparently misses resource status compatibility according to this [table](https://github.com/aztfmod/terraform-provider-azurecaf#resource-status).

It also requires the changes from [PR 277](https://github.com/Azure/caf-terraform-landingzones/pull/277) in [caf-terraform-landingzones](https://github.com/Azure/caf-terraform-landingzones).

2021-11-24 07:40 UTC, hyperfocus1337 commented
Currently not functional after new commits, working on fixing it.

2021-11-25 04:53 UTC, arnaudlh requested changes
thanks a lot for the PR @hyperfocus1337 - to go further, can you help us add: 

1. examples for CI/CD
2. documentation of the options
3. theres a dependency for the naming provider if you can append the name constraints and/or regex for the object, will help expedite the provider update - https://github.com/aztfmod/terraform-provider-azurecaf/issues/136

2021-11-25 04:53 UTC, arnaudlh commented on modules/monitoring/monitor_autoscale_settings/monitor_autoscale_settings.tf
> +  resource_type = "azurerm_monitor_autoscale_setting"
We will need to add support for that resource in the provider. I opened https://github.com/aztfmod/terraform-provider-azurecaf/issues/136 to track it

2021-11-25 08:39 UTC, hyperfocus1337 commented
Example renamed to 104 instead of 102 as the custom script and domain join extension from https://github.com/aztfmod/terraform-azurerm-caf/pull/807 will be prefixed to 102 and 103.

2021-11-26 14:05 UTC, hyperfocus1337 commented
Was able to get working output after running `terraform plan --var-file compute/virtual_machine_scale_set/102-linux-win-vmss-as-lb/configuration.tfvars` in the `examples` directory.

2021-11-26 14:19 UTC, hyperfocus1337 commented
Output result:

```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.example.azurecaf_name.public_ip_addresses["lb_pip1"] will be created
  + resource "azurecaf_name" "public_ip_addresses" {
      + clean_input   = true
      + id            = (known after apply)
      + name          = "lb_pip1"
      + passthrough   = false
      + prefixes      = (known after apply)
      + random_length = 0
      + resource_type = "azurerm_public_ip"
      + result        = (known after apply)
      + results       = (known after apply)
      + separator     = "-"
      + use_slug      = true
    }

  # module.example.azurecaf_name.public_ip_addresses["lb_pip2"] will be created
  + resource "azurecaf_name" "public_ip_addresses" {
      + clean_input   = true
      + id            = (known after apply)
      + name          = "lb_pip12"
      + passthrough   = false
      + prefixes      = (known after apply)
      + random_length = 0
      + resource_type = "azurerm_public_ip"
      + result        = (known after apply)
      + results       = (known after apply)
      + separator     = "-"
      + use_slug      = true
    }

  # module.example.random_string.prefix[0] will be created
  + resource "random_string" "prefix" {
      + id          = (known after apply)
      + length      = 4
      + lower       = true
      + min_lower   = 0
      + min_numeric = 0
      + min_special = 0
      + min_upper   = 0
      + number      = false
      + result      = (known after apply)
      + special     = false
      + upper       = false
    }

  # module.example.module.application_security_groups["app_sg1"].azurecaf_name.asg will be created
  + resource "azurecaf_name" "asg" {
      + clean_input   = true
      + id            = (known after apply)
      + name          = "app_sg1"
      + passthrough   = false
      + prefixes      = (known after apply)
      + random_length = 0
      + resource_type = "azurerm_application_security_group"
      + result        = (known after apply)
      + results       = (known after apply)
      + separator     = "-"
      + use_slug      = true
    }

  # module.example.module.application_security_groups["app_sg1"].azurerm_application_security_group.asg will be created
  + resource "azurerm_application_security_group" "asg" {
      + id                  = (known after apply)
      + location            = "southeastasia"
      + name                = (known after apply)
      + resource_group_name = (known after apply)
      + tags                = {
          + "module" = "application_security_group"
        }
    }

  # module.example.module.diagnostic_storage_accounts["bootdiag1"].azurecaf_name.stg will be created
  + resource "azurecaf_name" "stg" {
      + clean_input   = true
      + id            = (known after apply)
      + name          = "lebootdiag1"
      + passthrough   = false
      + prefixes      = (known after apply)
      + random_length = 0
      + resource_type = "azurerm_storage_account"
      + result        = (known after apply)
      + results       = (known after apply)
      + separator     = "-"
      + use_slug      = true
    }

  # module.example.module.diagnostic_storage_accounts["bootdiag1"].azurerm_storage_account.stg will be created
  + resource "azurerm_storage_account" "stg" {
      + access_tier                      = "Cool"
      + account_kind                     = "StorageV2"
      + account_replication_type         = "LRS"
      + account_tier                     = "Standard"
      + allow_blob_public_access         = false
      + enable_https_traffic_only        = true
      + id                               = (known after apply)
      + is_hns_enabled                   = false
      + large_file_share_enabled         = (known after apply)
      + location                         = "southeastasia"
      + min_tls_version                  = "TLS1_2"
      + name                             = (known after apply)
      + nfsv3_enabled                    = false
      + primary_access_key               = (sensitive value)
      + primary_blob_connection_string   = (sensitive value)
      + primary_blob_endpoint            = (known after apply)
      + primary_blob_host                = (known after apply)
      + primary_connection_string        = (sensitive value)
      + primary_dfs_endpoint             = (known after apply)
      + primary_dfs_host                 = (known after apply)
      + primary_file_endpoint            = (known after apply)
      + primary_file_host                = (known after apply)
      + primary_location                 = (known after apply)
      + primary_queue_endpoint           = (known after apply)
      + primary_queue_host               = (known after apply)
      + primary_table_endpoint           = (known after apply)
      + primary_table_host               = (known after apply)
      + primary_web_endpoint             = (known after apply)
      + primary_web_host                 = (known after apply)
      + resource_group_name              = (known after apply)
      + secondary_access_key             = (sensitive value)
      + secondary_blob_connection_string = (sensitive value)
      + secondary_blob_endpoint          = (known after apply)
      + secondary_blob_host              = (known after apply)
      + secondary_connection_string      = (sensitive value)
      + secondary_dfs_endpoint           = (known after apply)
      + secondary_dfs_host               = (known after apply)
      + secondary_file_endpoint          = (known after apply)
      + secondary_file_host              = (known after apply)
      + secondary_location               = (known after apply)
      + secondary_queue_endpoint         = (known after apply)
      + secondary_queue_host             = (known after apply)
      + secondary_table_endpoint         = (known after apply)
      + secondary_table_host             = (known after apply)
      + secondary_web_endpoint           = (known after apply)
      + secondary_web_host               = (known after apply)
      + shared_access_key_enabled        = true

      + blob_properties {
          + change_feed_enabled      = (known after apply)
          + default_service_version  = (known after apply)
          + last_access_time_enabled = (known after apply)
          + versioning_enabled       = (known after apply)

          + container_delete_retention_policy {
              + days = (known after apply)
            }

          + cors_rule {
              + allowed_headers    = (known after apply)
              + allowed_methods    = (known after apply)
              + allowed_origins    = (known after apply)
              + exposed_headers    = (known after apply)
              + max_age_in_seconds = (known after apply)
            }

          + delete_retention_policy {
              + days = (known after apply)
            }
        }

      + identity {
          + identity_ids = (known after apply)
          + principal_id = (known after apply)
          + tenant_id    = (known after apply)
          + type         = (known after apply)
        }

      + network_rules {
          + bypass                     = (known after apply)
          + default_action             = (known after apply)
          + ip_rules                   = (known after apply)
          + virtual_network_subnet_ids = (known after apply)

          + private_link_access {
              + endpoint_resource_id = (known after apply)
              + endpoint_tenant_id   = (known after apply)
            }
        }

      + queue_properties {
          + cors_rule {
              + allowed_headers    = (known after apply)
              + allowed_methods    = (known after apply)
              + allowed_origins    = (known after apply)
              + exposed_headers    = (known  [...]

2021-11-26 14:29 UTC, hyperfocus1337 commented
> * examples for CI/CD
> * documentation of the options
> * theres a dependency for the naming provider if you can append the name constraints and/or regex for the object, will help expedite the provider update - [aztfmod/terraform-provider-azurecaf#136](https://github.com/aztfmod/terraform-provider-azurecaf/issues/136)

These points previously mentioned by @arnaudlh still need to get done in order to finish the PR.

2021-11-26 14:59 UTC, hyperfocus1337 commented on examples/compute/virtual_machine_scale_set/104-linux-win-vmss-as-lb/configuration.tfvars
> +        # Note: use either recurrence or fixed_date
recurrence and fixed_date not yet functional after local testing

2021-11-26 15:01 UTC, hyperfocus1337 commented on examples/compute/virtual_machine_scale_set/104-linux-win-vmss-as-lb/configuration.tfvars
> +        # }
recurrence and fixed_date not yet functional after local testing

2021-12-03 03:15 UTC, arnaudlh requested changes
hi @hyperfocus1337 looks very good, maybe a few minor tweaks that you can do and we merge this one (optional fields and blocks, and also notification does not seem to work properly in my tests) thanks again for your PR!

2021-12-03 03:15 UTC, arnaudlh commented on modules/monitoring/monitor_autoscale_settings/monitor_autoscale_settings.tf
> +    for_each = try(var.settings.profiles.notification, {})
In my test, the notification settings did not seem to work, can you please double check?

2021-12-03 03:15 UTC, arnaudlh commented on modules/monitoring/monitor_autoscale_settings/monitor_autoscale_settings.tf
> +      email {
There is also ```webhook``` (multiple blocks) as per https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_autoscale_setting

2021-12-03 03:15 UTC, arnaudlh commented on modules/monitoring/monitor_autoscale_settings/monitor_autoscale_settings.tf
> +
enabled - option field as per https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_autoscale_setting

2021-12-03 03:15 UTC, arnaudlh commented on modules/monitoring/monitor_autoscale_settings/monitor_autoscale_settings.tf
> +            metric_name        = rule.value.metric_trigger.metric_name
metric_namespace (optional) and divide_by_instance_count, and dimensions block? - as per https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_autoscale_setting

2021-12-03 14:57 UTC, hyperfocus1337 commented on modules/monitoring/monitor_autoscale_settings/monitor_autoscale_settings.tf
> +      email {
Done, still need to add an example

2021-12-03 14:57 UTC, hyperfocus1337 commented on modules/monitoring/monitor_autoscale_settings/monitor_autoscale_settings.tf
> +
Option added

2021-12-03 14:58 UTC, hyperfocus1337 commented on modules/monitoring/monitor_autoscale_settings/monitor_autoscale_settings.tf
> +            metric_name        = rule.value.metric_trigger.metric_name
Still working on dimensions block and improve examples of the other two options

2021-12-03 14:59 UTC, hyperfocus1337 commented on modules/monitoring/monitor_autoscale_settings/monitor_autoscale_settings.tf
> +    for_each = try(var.settings.profiles.notification, {})
Works now

2021-12-03 15:00 UTC, hyperfocus1337 commented
Most recent local testing result returns:

```
# module.example.module.monitor_autoscale_settings["mas1"].azurerm_monitor_autoscale_setting.this will be created
  + resource "azurerm_monitor_autoscale_setting" "this" {
      + enabled             = true
      + id                  = (known after apply)
      + location            = "southeastasia"
      + name                = "mas1"
      + resource_group_name = (known after apply)
      + target_resource_id  = (known after apply)

      + notification {
          + email {
              + custom_emails                         = [
                  + "admin@contoso.com",
                ]
              + send_to_subscription_administrator    = true
              + send_to_subscription_co_administrator = true
            }
        }

      + profile {
          + name = "profile1"

          + capacity {
              + default = 1
              + maximum = 3
              + minimum = 1
            }

          + recurrence {
              + days     = [
                  + "Saturday",
                  + "Sunday",
                ]
              + hours    = [
                  + 12,
                ]
              + minutes  = [
                  + 0,
                ]
              + timezone = "Pacific Standard Time"
            }

          + rule {
              + metric_trigger {
                  + metric_name        = "Percentage CPU"
                  + metric_resource_id = (known after apply)
                  + operator           = "GreaterThan"
                  + statistic          = "Average"
                  + threshold          = 90
                  + time_aggregation   = "Average"
                  + time_grain         = "PT1M"
                  + time_window        = "PT5M"
                }

              + scale_action {
                  + cooldown  = "PT1M"
                  + direction = "Increase"
                  + type      = "ChangeCount"
                  + value     = 2
                }
            }
        }
    }
```

Still need to finish dimensions and a few examples.

2021-12-06 12:55 UTC, hyperfocus1337 commented on modules/monitoring/monitor_autoscale_settings/monitor_autoscale_settings.tf
> +      email {
Example added

2021-12-06 12:55 UTC, hyperfocus1337 commented on modules/monitoring/monitor_autoscale_settings/monitor_autoscale_settings.tf
> +            metric_name        = rule.value.metric_trigger.metric_name
Dimensions block working

2021-12-06 12:56 UTC, hyperfocus1337 commented
Comments resolved, looking forward to the review and potential merge

2021-12-08 04:59 UTC, arnaudlh approved these changes
LGTM

2021-12-08 05:00 UTC, merged

2021-12-08 05:00 UTC, arnaudlh commented
thanks for your contribution @hyperfocus1337!