Add support for vmss custom script and domain join extensions
aztfmod/terraform-azurerm-caf pull request #807
Opened 2021-11-18 15:32 UTC by hyperfocus1337

Related to [PR 278](https://github.com/Azure/caf-terraform-landingzones/pull/278) in [caf-terraform-landingzones](https://github.com/Azure/caf-terraform-landingzones).

Local plan succeeded using the following commands:

```
cd examples/vmss_extensions.tf.
terraform plan -var-file compute/virtual_machine_scale_set/102-linux-win-vmss-custom-script-extension/configuration.tfvars
```

2021-11-23 01:16 UTC, LaurentLesle approved these changes
Thanks @hyperfocus1337. Great addition. Thanks. Going to test before commit

2021-11-23 09:13 UTC, arnaudlh requested changes
Thanks for your PR @hyperfocus1337 - i found a couple of small hiccups in the custom script config sample file. Can you please address them and also add it to CI/CD test adding the example 102 ```standalone-scenarios.json```. Havent tried ADDJ yet.

2021-11-23 09:13 UTC, arnaudlh commented on examples/compute/virtual_machine_scale_set/102-linux-win-vmss-custom-script-extension/configuration.tfvars
> +            keys = ["user_mi"]
Wrong key - example_mi?

2021-11-23 09:13 UTC, arnaudlh commented on examples/compute/virtual_machine_scale_set/102-linux-win-vmss-custom-script-extension/configuration.tfvars
> +    keyvault_key                         = "kv1"
wrong key - example_vm_rg1?

2021-11-23 09:13 UTC, arnaudlh commented on examples/compute/virtual_machine_scale_set/102-linux-win-vmss-custom-script-extension/configuration.tfvars
> +    virtual_machine_scale_set_extensions = {
Maybe provide a bash example for Linux and include a sample bash script?

2021-11-23 09:13 UTC, arnaudlh commented on examples/compute/virtual_machine_scale_set/102-linux-win-vmss-custom-script-extension/configuration.tfvars
> +    keyvault_key                         = "kv1"
Wrong key: example_vm_rg1?

2021-11-23 09:13 UTC, arnaudlh commented on examples/compute/virtual_machine_scale_set/102-linux-win-vmss-custom-script-extension/configuration.tfvars
> +      custom_script = {
The file hello world file seems to be missing in the example folder.

2021-11-23 09:13 UTC, arnaudlh commented on examples/compute/virtual_machine_scale_set/102-linux-win-vmss-custom-script-extension/configuration.tfvars
> +          remote = {
comment it to show the usage - otherwise might create issues when people run it.

2021-11-23 10:47 UTC, hyperfocus1337 commented on examples/compute/virtual_machine_scale_set/102-linux-win-vmss-custom-script-extension/configuration.tfvars
> +    keyvault_key                         = "kv1"
In other virtual machine scale set examples it's also `rg1`: https://github.com/aztfmod/terraform-azurerm-caf/blob/master/examples/compute/virtual_machine_scale_set/101-linux-win-vmss-agw/configuration.tfvars#L9

But, I have just changed it to `example_vm_rg1`

2021-11-23 13:08 UTC, hyperfocus1337 commented on examples/compute/virtual_machine_scale_set/102-linux-win-vmss-custom-script-extension/configuration.tfvars
> +    keyvault_key                         = "kv1"
Actually, `example_vmss_rg1` makes more sense, updated

2021-11-23 14:12 UTC, hyperfocus1337 commented on examples/compute/virtual_machine_scale_set/102-linux-win-vmss-custom-script-extension/configuration.tfvars
> +            keys = ["user_mi"]
Changed to `example_vmss_kv1`

2021-11-23 14:14 UTC, hyperfocus1337 commented on examples/compute/virtual_machine_scale_set/102-linux-win-vmss-custom-script-extension/configuration.tfvars
> +    virtual_machine_scale_set_extensions = {
Formatted and improved the comments and included sample `helloworld.sh`, but untested so far

2021-11-24 03:59 UTC, arnaudlh requested changes
I still dont have it working @hyperfocus1337 - you need to add the linux script to its to blob storage :

```
storage_account_blobs = {
  script = {
    name                   = "helloworld.ps1"
    storage_account_key    = "sa1"
    storage_container_name = "files"
    source                 = "./compute/virtual_machine_scale_set/102-linux-win-vmss-custom-script-extension/helloworld.ps1"
    parallelism            = 1
  }
}
```

Also, have you tested and checked within the VM is the extension is working? Showing it successful on the portal/Extension is not enough, need to make sure the execution inside the VM instance is correct. I wasnot able to see that in my tests.

thanks!
arnaud

2021-11-24 03:59 UTC, arnaudlh commented on examples/compute/virtual_machine_scale_set/102-linux-win-vmss-custom-script-extension/scripts/helloworld.ps1
> +Write-Host "Hello, World!"
Start-Transcript -Path c:\helloworld.txt
write-output "hello world"
stop-transcript

2021-11-24 03:59 UTC, arnaudlh commented on examples/compute/virtual_machine_scale_set/102-linux-win-vmss-custom-script-extension/scripts/helloworld.ps1
> +Write-Host "Hello, World!"
maybe something like that to have a trace?

2021-11-24 03:59 UTC, arnaudlh commented on examples/compute/virtual_machine_scale_set/102-linux-win-vmss-custom-script-extension/scripts/helloworld.sh
> +echo "Hello, World!"
#!/usr/bin/env bash

echo "Hello, World!" > hello.log

2021-11-24 03:59 UTC, arnaudlh commented on examples/compute/virtual_machine_scale_set/102-linux-win-vmss-custom-script-extension/scripts/helloworld.sh
> +echo "Hello, World!"
maybe something like that to have a trace?

2021-11-24 09:46 UTC, hyperfocus1337 commented on examples/compute/virtual_machine_scale_set/102-linux-win-vmss-custom-script-extension/scripts/helloworld.ps1
> +Write-Host "Hello, World!"
Included, testing

2021-11-24 09:47 UTC, hyperfocus1337 commented on examples/compute/virtual_machine_scale_set/102-linux-win-vmss-custom-script-extension/scripts/helloworld.sh
> +echo "Hello, World!"
Included, testing

2021-12-08 03:46 UTC, arnaudlh approved these changes

2021-12-08 04:23 UTC, arnaudlh commented
thanks for the PR @hyperfocus1337 I'll go ahead and merge to master with a few corrections.

2021-12-08 04:23 UTC, merged