Add automatic repair to vmss, based on a lb probe.
aztfmod/terraform-azurerm-caf pull request #844
Opened 2021-12-06 13:33 UTC by robertdebock

Hi,

This PR should resolve #829.

I've tried it locally, it works; delivered healthy vmss instances and is idempotent.

Please let me know if this is good enough to merge.

2021-12-09 10:29 UTC, arnaudlh requested changes
thanks @robertdebock for the PR, couple of things to change but looks like a good addition!

2021-12-09 10:29 UTC, arnaudlh commented on modules/compute/virtual_machine_scale_set/vmss_linux.tf
> +  health_probe_id = var.load_balancers[try(each.value.lz_key, var.client_config.landingzone_key)][each.value.health_probe.loadbalancer_key].probes[each.value.health_probe.probe_key].id
This will introduce a regression for cases where theres no health_probe_id. 
I'd suggest you add a try that ends with a null and also allow specifying an already existing lb by its resource id.

2021-12-09 10:29 UTC, arnaudlh commented on modules/compute/virtual_machine_scale_set/vmss_windows.tf
> +  health_probe_id = var.load_balancers[try(each.value.lz_key, var.client_config.landingzone_key)][each.value.health_probe.loadbalancer_key].probes[each.value.health_probe.probe_key].id
This will introduce a regression for cases where theres no health_probe_id. 
I'd suggest you add a try that ends with a null and also allow specifying an already existing lb by its resource id.

2021-12-09 10:52 UTC, robertdebock commented on modules/compute/virtual_machine_scale_set/vmss_linux.tf
> +  health_probe_id = var.load_balancers[try(each.value.lz_key, var.client_config.landingzone_key)][each.value.health_probe.loadbalancer_key].probes[each.value.health_probe.probe_key].id
Thanks, I understand:

> This will introduce a regression for cases where theres no health_probe_id. I'd suggest you add a try that ends with a null.

I don't understand this feedback:

> And also allow specifying an already existing lb by its resource id.

Do you mean that you'd like the users of this module to specify a "load balancer id" instead of looking the id up using this map:

```hcl
        health_probe = {
          loadbalancer_key = "lb1"
          probe_key        = "probe1"
        }
```

2021-12-09 15:45 UTC, robertdebock commented on modules/compute/virtual_machine_scale_set/vmss_linux.tf
> +  health_probe_id = var.load_balancers[try(each.value.lz_key, var.client_config.landingzone_key)][each.value.health_probe.loadbalancer_key].probes[each.value.health_probe.probe_key].id
Just pushed the `try`, making `health_probe_id` optional.

I think the items are resolved, let me know if this remark requires further work:

```
And also allow specifying an already existing lb by its resource id.
> Do you mean that you'd like the users of this module to specify a "load balancer id" instead of looking the id up using this map:
```

2021-12-09 15:46 UTC, robertdebock commented on modules/compute/virtual_machine_scale_set/vmss_windows.tf
> +  health_probe_id = var.load_balancers[try(each.value.lz_key, var.client_config.landingzone_key)][each.value.health_probe.loadbalancer_key].probes[each.value.health_probe.probe_key].id
That's implemented with the last commit.

2022-01-04 08:40 UTC, robertdebock commented
Hi, and a happy new year!

Are there further changes required to this PR?

2022-01-05 04:22 UTC, arnaudlh approved these changes
LGTM

2022-01-05 04:23 UTC, merged

2022-01-05 04:23 UTC, arnaudlh commented
> Hi, and a happy new year!
> 
> Are there further changes required to this PR?

Looks good to me, thanks for your contribution @robertdebock!