Azurefile nfs
aztfmod/terraform-azurerm-caf pull request #862
Opened 2021-12-11 03:42 UTC by hriaz

Fixes #861 

Introduces support for Azure File share NFS support.

2022-01-05 07:31 UTC, arnaudlh requested changes
thanks for the contribution @hriaz, looks good to me, do you mind adding examples for CI/CD and also visibility? thanks!

2022-01-27 22:40 UTC, hriaz commented
@arnaudlh Will do thanks.

2022-04-04 08:17 UTC, arnaudlh commented
Testing and getting: 

╷
│ Error: Missing required argument
│ 
│   on ../modules/storage_account/file_share/file_share.tf line 15, in resource "azurerm_storage_share" "fs":
│   15:       dynamic "access_policy" {
│ 
│ The argument "for_each" is required, but no definition was found.
╵
Terraform plan return code: 1

@hriaz - Can you please have a look if you want this one merged? thanks!

2022-04-07 01:28 UTC, hriaz commented
> Testing and getting:
> 
> ╷ │ Error: Missing required argument │ │ on ../modules/storage_account/file_share/file_share.tf line 15, in resource "azurerm_storage_share" "fs": │ 15: dynamic "access_policy" { │ │ The argument "for_each" is required, but no definition was found. ╵ Terraform plan return code: 1
> 
> @hriaz - Can you please have a look if you want this one merged? thanks!

Please test. Updated try block and added to CI including example

2022-04-12 11:30 UTC, arnaudlh requested changes
Almost there :)

2022-04-12 11:30 UTC, arnaudlh commented on modules/storage_account/file_share/file_share.tf
> +  enabled_protocol     = try(var.settings.enabled_protocol, "SMB")
```suggestion
  enabled_protocol     = try(var.settings.enabled_protocol, null)
```

2022-04-12 11:30 UTC, arnaudlh commented on examples/storage_accounts/108-file-share-nfs/configuration.tfvars
> +    network = {
Comment that section or deployment does not succeed.

2022-04-25 09:49 UTC, arnaudlh approved these changes
LGTM

2022-04-25 09:52 UTC, merged