Update private_endpoint.tf
aztfmod/terraform-azurerm-caf pull request #866
Opened 2021-12-13 10:27 UTC by rickychew77

as existing applied tfvars and example are using `private_dns` instead of `private_dns_zone_group`, reverting this to avoid breaking changes

2021-12-13 23:46 UTC, iriahk89 requested changes
add try block to handle both existing and new implementation:
try(private_dns.zone_group_name, private_dns_zone_group.zone_group_name)

2021-12-13 23:53 UTC, iriahk89 commented on modules/networking/private_endpoint/private_endpoint.tf
> +      name = private_dns.zone_group_name
should it be var.settings.private_dns.zone_group_name? if not where did the value for private_dns came from?

2021-12-14 01:07 UTC, rickychew77 commented on modules/networking/private_endpoint/private_endpoint.tf
> +      name = private_dns.zone_group_name
agreed, let's use `try(var.settings.private_dns.zone_group_name, private_dns_zone_group.zone_group_name)`

2022-01-04 07:48 UTC, iriahk89 approved these changes
LGTM

2022-01-04 09:18 UTC, merged