add ability for keyvault to reference existing subnet by id
aztfmod/terraform-azurerm-caf pull request #889
Opened 2022-01-06 03:21 UTC by cldcvr-stefan

2022-01-06 03:23 UTC, cldcvr-stefan commented
resolves #880

2022-01-06 10:53 UTC, arnaudlh requested changes
Thanks for your PR @cldcvr-stefan, since the attribute ```virtual_network_subnet_ids``` is allowing a list of subnet IDs, maybe we can reflect the plural as well in the variable name --> ```value.subnet_ids```?

2022-01-06 10:53 UTC, arnaudlh commented on modules/security/keyvault/keyvault.tf
> +        for key, value in var.settings.network.subnets : try(var.vnets[var.client_config.landingzone_key][value.vnet_key].subnets[value.subnet_key].id, try(var.vnets[value.lz_key][value.vnet_key].sub
Thanks for your PR @cldcvr-stefan, since the attribute ```virtual_network_subnet_ids``` is allowing a list of subnet IDs, maybe we can reflect the plural as well in the variable name --> ```value.subnet_ids```?

2022-01-06 12:10 UTC, cldcvr-stefan commented on modules/security/keyvault/keyvault.tf
> +        for key, value in var.settings.network.subnets : try(var.vnets[var.client_config.landingzone_key][value.vnet_key].subnets[value.subnet_key].id, try(var.vnets[value.lz_key][value.vnet_key].sub
Hi @arnaudlh looking at the use case, the code seems to be iterating through each network.subnets object to build the list of ips in virtual_network_subnet_ids, so in each iteration it would only be referencing a single subnet.

2022-01-10 09:15 UTC, arnaudlh approved these changes

2022-01-10 09:15 UTC, merged